//
//  ball.c
//
//  Generated by Melia on 24/05/2023.
//

#include "ball.h"

#include "circularshootingstyle.h"
#include "../gen/spritenames.h"
#include "../gen/spriteball.h"
#include "../gen/spritebullet.h"

enum ball_state {
    appearing,
    main,
    withdrawing,
};

struct ball {
    MELSprite super;

    enum ball_state state;
    uint8_t statePart;
    MELDirection shotDirection;
    ShootingStyle style;
    float time;
};

static void appearingStatePart0(LCDSprite * _Nonnull sprite);
static void appearingStatePart1(LCDSprite * _Nonnull sprite);

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct ball * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass BallClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

static const CircularShootingStyleDefinition kStyleDefinition = (CircularShootingStyleDefinition) {
    .super = {
        .bulletDefinition = &spriteBullet,
        .bulletSpeed = 75,
        .bulletAmount = 3,
        .damage = ENEMY_BALL_BULLET_DAMAGE,
        .shootInterval = 0.3f,
    },
    .angleIncrement = MEL_2_PI / 3.0f,
};

LCDSprite * _Nonnull BallConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct ball *self = playdate->system->realloc(NULL, sizeof(struct ball));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &BallClass;
    self->super.hitPoints = ENEMY_BALL_HIT_POINTS;
    self->super.score = ENEMY_BALL_SCORE;
    self->shotDirection = MELDirectionLeft;
    MELSpriteSetAnimation(&self->super, AnimationNameAppear);
    self->super.frame.origin.y = 240;
    self->state = appearing;
    self->statePart = 0;
    loadSpriteBulletPalette();
    CircularShootingStyleInit(&self->style, &kStyleDefinition);
    playdate->sprite->setUpdateFunction(sprite, &appearingStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct ball *self = (struct ball *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteByte(outputStream, self->shotDirection);
    ShootingStyleSave(&self->style, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable BallLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct ball *self = playdate->system->realloc(NULL, sizeof(struct ball));
    const enum ball_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const MELDirection shotDirection = MELInputStreamReadByte(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kStyleDefinition.super);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct ball) {
        .super = {
            .class = &BallClass
        },
        .state = state,
        .statePart = statePart,
        .shotDirection = shotDirection,
        .style = style,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct ball * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case main:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, appearingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, appearingStatePart0);
                    break;
            }
            break;
    }
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void draw(struct ball * _Nonnull self, LCDSprite * _Nonnull sprite) {
    MELPoint origin = self->super.frame.origin;
    origin.x += (MELDirectionValues[self->super.direction] * DELTA) * 6.0f;
    if (origin.x < -32.0f) {
        MELSpriteDealloc(sprite);
        return;
    }
    self->super.frame.origin = origin;
    MELSpriteDraw(&self->super, sprite);
}

static void appearingStatePart0(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    MELSpriteSetAnimation(&self->super, AnimationNameAppear);
    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &appearingStatePart1);

    draw(self, sprite);
}

static void appearingStatePart1(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.75f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = 240 + (self->super.instance->center.y - 240) * progress;
        draw(self, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    draw(self, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 3.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;
        const float progress = MELEaseInOut(0, duration, newTime);

        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MELDirectionValues[self->super.direction] * progress * MEL_PI_2);
        draw(self, sprite);
        return;
    }
    self->shotDirection = MELDirectionReverses[self->shotDirection];
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    draw(self, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(self, sprite);
        return;
    }
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    MELSpriteSetAnimation(&self->super, AnimationNameDisappear);
    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    draw(self, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct ball *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.75f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = self->super.instance->center.y + (240 - self->super.instance->center.y) * progress;
        draw(self, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

