//
//  boat.c
//
//  Generated by Melia on 19/05/2023.
//

#include "boat.h"

#include "../gen/spritenames.h"
#include "../gen/spriteboat.h"

enum boat_state {
    entering,
    main,
    withdrawing,
};

struct boat {
    MELSprite super;

    enum boat_state state;
    uint8_t statePart;
    float direction;
    float strideDecimalFrom0;
    float strideDecimalFrom1;
    float strideDecimalTo0;
    float strideDecimalTo1;
    float time;
    float wobble;
    float wobbleSpeed;
};

static void enteringStatePart0(LCDSprite * _Nonnull sprite);
static void enteringStatePart1(LCDSprite * _Nonnull sprite);

static void mainStatePart0(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct boat * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

const MELSpriteClass BoatClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

LCDSprite * _Nonnull BoatConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct boat *self = playdate->system->realloc(NULL, sizeof(struct boat));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &BoatClass;
    self->super.hitPoints = ENEMY_BOAT_HIT_POINTS;
    self->super.score = ENEMY_BOAT_SCORE;
    self->super.frame.origin.y = -24.0f;
    self->wobble = 0;
    self->wobbleSpeed = MELRandomFloat(2.0f) - 1.0f;
    self->state = entering;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &enteringStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct boat *self = (struct boat *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->direction);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalFrom0);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalFrom1);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalTo0);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalTo1);
    MELOutputStreamWriteFloat(outputStream, self->time);
    MELOutputStreamWriteFloat(outputStream, self->wobble);
    MELOutputStreamWriteFloat(outputStream, self->wobbleSpeed);
}

MELSprite * _Nullable BoatLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct boat *self = playdate->system->realloc(NULL, sizeof(struct boat));
    const enum boat_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float direction = MELInputStreamReadFloat(inputStream);
    const float strideDecimalFrom0 = MELInputStreamReadFloat(inputStream);
    const float strideDecimalFrom1 = MELInputStreamReadFloat(inputStream);
    const float strideDecimalTo0 = MELInputStreamReadFloat(inputStream);
    const float strideDecimalTo1 = MELInputStreamReadFloat(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);
    const float wobble = MELInputStreamReadFloat(inputStream);
    const float wobbleSpeed = MELInputStreamReadFloat(inputStream);

    *self = (struct boat) {
        .super = {
            .class = &BoatClass
        },
        .state = state,
        .statePart = statePart,
        .direction = direction,
        .strideDecimalFrom0 = strideDecimalFrom0,
        .strideDecimalFrom1 = strideDecimalFrom1,
        .strideDecimalTo0 = strideDecimalTo0,
        .strideDecimalTo1 = strideDecimalTo1,
        .time = time,
        .wobble = wobble,
        .wobbleSpeed = wobbleSpeed,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct boat * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case main:
            playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
            break;
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, enteringStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, enteringStatePart0);
                    break;
            }
            break;
    }
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct boat *self = playdate->sprite->getUserdata(sprite);
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void enteringStatePart0(LCDSprite * _Nonnull sprite) {
    struct boat *self = playdate->sprite->getUserdata(sprite);

    if (self->super.instance->center.y < LCD_ROWS / 2) {
        self->direction = (-LCD_ROWS + MELRandomFloat(32.0f)) - 16.0f;
    } else {
        self->direction = LCD_ROWS - MELRandomFloat(32.0f) + 16.0f;
    }
    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &enteringStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void enteringStatePart1(LCDSprite * _Nonnull sprite) {
    struct boat *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + 90 * (1.0f - progress);
        self->super.frame.origin.y = self->super.instance->center.y + (self->direction * (1.0f - progress)) * (1.0f - progress);
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct boat *self = playdate->sprite->getUserdata(sprite);

    self->wobble = self->wobble + DELTA * self->wobbleSpeed;
    self->super.frame.origin.x = self->super.frame.origin.x - DELTA * 8.0f;
    self->super.frame.origin.y = self->super.instance->center.y + sinf(self->wobble) * 4.0f;
    if (self->super.frame.origin.x < -32.0f) {
        MELSpriteDealloc(sprite);
        return;
    }
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct boat *self = playdate->sprite->getUserdata(sprite);

    // during
    self->strideDecimalFrom0 = self->super.frame.origin.x;
    self->strideDecimalTo0 = self->super.frame.origin.x - 90;
    self->strideDecimalFrom1 = self->super.frame.origin.y;
    self->strideDecimalTo1 = self->super.frame.origin.y + self->direction;
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct boat *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->strideDecimalFrom0 + (self->strideDecimalTo0 - self->strideDecimalFrom0) * progress;
        self->super.frame.origin.y = self->strideDecimalFrom1 + (self->strideDecimalTo1 - self->strideDecimalFrom1) * (progress * progress);
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

