//
//  capsule.c
//
//  Generated by Melia on 24/05/2023.
//

#include "capsule.h"

#include "camera.h"
#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spritecapsule.h"

enum capsule_state {
    main,
    withdrawing,
};

struct capsule {
    MELSprite super;

    enum capsule_state state;
    uint8_t statePart;
    float time;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct capsule * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass CapsuleClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

LCDSprite * _Nonnull CapsuleConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct capsule *self = playdate->system->realloc(NULL, sizeof(struct capsule));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &CapsuleClass;
    self->super.hitPoints = ENEMY_CAPSULE_HIT_POINTS;
    self->super.score = ENEMY_CAPSULE_SCORE;
    self->super.frame.origin.x = 442.0f;
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct capsule *self = (struct capsule *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable CapsuleLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct capsule *self = playdate->system->realloc(NULL, sizeof(struct capsule));
    const enum capsule_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct capsule) {
        .super = {
            .class = &CapsuleClass
        },
        .state = state,
        .statePart = statePart,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct capsule *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &CapsuleClass) {
        playdate->system->error("Given sprite is not an instance of Capsule");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void goToCurrentState(struct capsule * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct capsule *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct capsule *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 442.0f + (self->super.instance->center.x - 442.0f) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // while
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);
    mainStatePart2(sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct capsule *self = playdate->sprite->getUserdata(sprite);

    // while
    // wait
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct capsule *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct capsule *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + 400 * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}
