//
//  character_select_crank.c
//
//  Generated by Melia on 26/08/2023.
//

#include "character_select_crank.h"

#include "character_select_common.h"
#include "../gen/spritenames.h"
#include "../gen/spritecharacterselectcrank.h"

enum character_select_crank_state {
    katsuo,
    changeToSaki,
    saki,
    changeToKatsuo,
};

struct character_select_crank {
    MELSprite super;
    PlayerCharacter * _Nonnull selection;

    enum character_select_crank_state state;
    uint8_t statePart;
    float time;
};

static void katsuoStatePart0(LCDSprite * _Nonnull sprite);

static void changeToSakiStatePart0(LCDSprite * _Nonnull sprite);
static void changeToSakiStatePart1(LCDSprite * _Nonnull sprite);
static void changeToSakiStatePart2(LCDSprite * _Nonnull sprite);

static void sakiStatePart0(LCDSprite * _Nonnull sprite);

static void changeToKatsuoStatePart0(LCDSprite * _Nonnull sprite);
static void changeToKatsuoStatePart1(LCDSprite * _Nonnull sprite);
static void changeToKatsuoStatePart2(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct character_select_crank * _Nonnull self, LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass CharacterSelectCrankClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
};

LCDSprite * _Nonnull CharacterSelectCrankConstructorWithSelection(PlayerCharacter * _Nonnull selection) {
    struct character_select_crank *self = playdate->system->realloc(NULL, sizeof(struct character_select_crank));
    loadSpriteCharacterSelectCrankPalette();

    const MELBoolean isKatsuo = *selection == PlayerCharacterKatsuo;
    const MELPoint origin = (MELPoint) {
        .x = isKatsuo ? 352.0f : 32.0f,
        .y = 208.0f
    };

    LCDSprite *sprite = MELSpriteInitWithCenter(&self->super, &spriteCharacterSelectCrank, origin);
    self->super.class = &CharacterSelectCrankClass;
    self->selection = selection;
    self->statePart = 0;
    if (isKatsuo) {
        self->state = katsuo;
        MELSpriteSetAnimation(&self->super, AnimationNameRun);
        playdate->sprite->setUpdateFunction(sprite, katsuoStatePart0);
    } else {
        self->state = saki;
        MELSpriteSetAnimation(&self->super, AnimationNameWalk);
        playdate->sprite->setUpdateFunction(sprite, sakiStatePart0);
    }
#if LOG_SPRITE_PUSH_AND_REMOVE_FROM_SCENE_SPRITES
    playdate->system->logToConsole("Push CharacterSelectCrankConstructorWithSelection(%x, %x): %d", sprite, self, self->super.definition.name);
#endif
    LCDSpriteRefListPush(&currentScene->sprites, sprite);
    return sprite;
}

LCDSprite * _Nonnull CharacterSelectCrankConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct character_select_crank *self = playdate->system->realloc(NULL, sizeof(struct character_select_crank));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &CharacterSelectCrankClass;
    MELSpriteSetAnimation(&self->super, AnimationNameRun);
    self->super.frame.origin = (MELPoint) {
        .x = 352.0f,
        .y = 208.0f
    };
    self->state = katsuo;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &katsuoStatePart0);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct character_select_crank *self = (struct character_select_crank *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable CharacterSelectCrankLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct character_select_crank *self = playdate->system->realloc(NULL, sizeof(struct character_select_crank));
    const enum character_select_crank_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct character_select_crank) {
        .super = {
            .class = &CharacterSelectCrankClass
        },
        .state = state,
        .statePart = statePart,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct character_select_crank * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case changeToSaki:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, changeToSakiStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, changeToSakiStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, changeToSakiStatePart0);
                    break;
            }
            break;
        case saki:
            playdate->sprite->setUpdateFunction(sprite, sakiStatePart0);
            break;
        case changeToKatsuo:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, changeToKatsuoStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, changeToKatsuoStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, changeToKatsuoStatePart0);
                    break;
            }
            break;
        default:
            playdate->sprite->setUpdateFunction(sprite, katsuoStatePart0);
            break;
    }
}

static void draw(struct character_select_crank * _Nonnull self, LCDSprite * _Nonnull sprite) {
    MELAnimationUpdate(self->super.animation, DELTA);

    const MELPoint origin = self->super.frame.origin;
    playdate->sprite->moveTo(sprite, origin.x, origin.y);
    playdate->sprite->setImage(sprite, playdate->graphics->getTableBitmap(self->super.definition.palette, self->super.animation->frame.atlasIndex), kBitmapUnflipped);
}

static void katsuoStatePart0(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    if (*self->selection != PlayerCharacterKatsuo) {
        self->state = changeToSaki;
        self->statePart = 0;
        playdate->sprite->setUpdateFunction(sprite, changeToSakiStatePart0);
    }

    draw(self, sprite);
}

static void changeToSakiStatePart0(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &changeToSakiStatePart1);

    draw(self, sprite);
}

static void changeToSakiStatePart1(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = kHalfAnimationDuration;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = 208.0f + 64.0f * progress;
        draw(self, sprite);
        return;
    }
    MELSpriteSetAnimation(&self->super, AnimationNameWalk);
    self->super.frame.origin.x = 32.0f;
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &changeToSakiStatePart2);

    draw(self, sprite);
}

static void changeToSakiStatePart2(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = kHalfAnimationDuration;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = 272.0f + -64.0f * progress;
        draw(self, sprite);
        return;
    }
    self->state = saki;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void sakiStatePart0(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    if (*self->selection != PlayerCharacterSaki) {
        self->state = changeToKatsuo;
        self->statePart = 0;
        playdate->sprite->setUpdateFunction(sprite, changeToKatsuoStatePart0);
    }

    draw(self, sprite);
}

static void changeToKatsuoStatePart0(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &changeToKatsuoStatePart1);

    draw(self, sprite);
}

static void changeToKatsuoStatePart1(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = kHalfAnimationDuration;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = 208.0f + 64.0f * progress;
        draw(self, sprite);
        return;
    }
    MELSpriteSetAnimation(&self->super, AnimationNameRun);
    self->super.frame.origin.x = 352.0f;
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &changeToKatsuoStatePart2);

    draw(self, sprite);
}

static void changeToKatsuoStatePart2(LCDSprite * _Nonnull sprite) {
    struct character_select_crank *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = kHalfAnimationDuration;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = 272.0f + -64.0f * progress;
        draw(self, sprite);
        return;
    }
    self->state = katsuo;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

