//
//  common.h
//  Kuroobi
//
//  Created by Raphaël Calabro on 23/01/2023.
//

#ifndef common_h
#define common_h

#include "pd_api.h"
#include "../lib/melstd.h"

#define VERSION_NUMBER "1.2.1"

#define ENABLE_ONLINE_SCOREBOARDS 0
#define ENABLE_SHOOTING_STYLE_INVERSIONS 0
#define ENABLE_GAME_CARD 0

#define CHECK_CLASS_CAST 1
#define CHECK_LAYERSPRITE_MAP_WIDTH 1

#define LOG_CATCHES_AND_THROWS 0
#define LOG_WAVE_CHANGES 0
#define LOG_SPRITE_PUSH_AND_REMOVE_FROM_SCENE_SPRITES 0
#define LOG_SAVES 0

#define DEFAULT_REFRESH_RATE 50
#define DEFAULT_FRAME_TIME (1.0f / DEFAULT_REFRESH_RATE)
#define SHOW_FRAME_RATE 0

#define CAMERA_SPEED 200.0f
#define CAMERA_SPEED_UP_DURING_BOSS_GUNNER 300.0f

#define FORWARD_ANGLE 90.0f

#define ONEUP_SCORE 50000
#define MAXIMUM_LIFE_COUNT 6
#define MAXIMUM_LIFE_SCORE_BONUS 1000

#define COMBO_DURATION 4.0f

#define ENEMY_BALL_HIT_POINTS 60
#define ENEMY_BALL_BULLET_DAMAGE 2
#define ENEMY_BALL_SCORE 420

#define ENEMY_BOAT_HIT_POINTS 30
#define ENEMY_BOAT_SCORE 50

#define ENEMY_CAPSULE_HIT_POINTS 50
#define ENEMY_CAPSULE_SCORE 110

#define ENEMY_DUCKTOOL_HIT_POINTS 45
#define ENEMY_DUCKTOOL_BULLET_DAMAGE 1
#define ENEMY_DUCKTOOL_SCORE 155

#define ENEMY_GUNBEE_HIT_POINTS 90
#define ENEMY_GUNBEE_BULLET_DAMAGE 2
#define ENEMY_GUNBEE_SCORE 290

#define ENEMY_JESTER_HIT_POINTS 40
#define ENEMY_JESTER_SCORE 60

#define ENEMY_RAPID_FIRE_HIT_POINTS 80
#define ENEMY_RAPID_FIRE_BULLET_DAMAGE 2
#define ENEMY_RAPID_FIRE_SCORE 280

#define ENEMY_ROTATING_HIT_POINTS 10
#define ENEMY_ROTATING_BULLET_DAMAGE 1
#define ENEMY_ROTATING_SCORE 75

#define ENEMY_SINUSOIDAL_HIT_POINTS 25
#define ENEMY_SINUSOIDAL_SCORE 180

#define ENEMY_SHARK_HIT_POINTS 70
#define ENEMY_SHARK_BULLET_DAMAGE 2
#define ENEMY_SHARK_SCORE 390

#define ENEMY_STATIONARY_HIT_POINTS 50
#define ENEMY_STATIONARY_BULLET_DAMAGE 2
#define ENEMY_STATIONARY_SCORE 140

#define ENEMY_SATELLITE_HIT_POINTS 90
#define ENEMY_SATELLITE_BULLET_DAMAGE 3
#define ENEMY_SATELLITE_SCORE 370

#define BOSS_MID_HIT_POINTS 150
#define BOSS_MID_SCORE 10000
#define BOSS_MID_ROCKET_DAMAGE 50

#define BOSS_MID_AUX_HIT_POINTS 50
#define BOSS_MID_AUX_BULLET_DAMAGE 1
#define BOSS_MID_AUX_SCORE 500

#define BOSS_SATELLITE_AUX_HIT_POINTS 75
#define BOSS_SATELLITE_AUX_BULLET_DAMAGE 1
#define BOSS_SATELLITE_AUX_SCORE 50

#define BOSS_SATELLITE_HIT_POINTS 1000
#define BOSS_SATELLITE_SCORE 30000

#define BOSS_GUNNER_HIT_POINTS 3
#define BOSS_GUNNER_SCORE 50000
#define BOSS_GUNNER_BULLET_DAMAGE 1

#define PLAYER_COLLISION_DAMAGE 20
#define PLAYER_INVICIBILITY_DURATION 3.0f

#define BULLET_SCORE_MULTIPLIER 5

#define ENEMY_HIT_DURATION 0.2f
#define THROWN_ENEMY_INTERVAL_BETWEEN_HITPOINT_LOSS 0.5f
#define THROWN_ENEMY_DAMAGE_ON_BOUNCE 5

#define CAUGHT_RELEASE_SPEED_WHEN_PLAYER_IS_DESTROYED 50

#define GAME_TOTAL_TIME_IN_SECONDS 180
#define SECONDS_IN_A_MINUTE 60

#define LIFE_LEFT_SCORE_BONUS 5000
#define SECOND_LEFT_SCORE_BONUS 500
#define COMBO_SCORE_BONUS 50

#define RANK_CHOU_S_TIME_LEFT 35
#define RANK_CHOU_S_COMBO 170

#define FONT_NUMBERS_HEIGHT 12
#define FONT_ROMAJI_HEIGHT 16
#define FONT_RAINS2X_HEIGHT 14

#define GUI_PADDING 5
#define GUI_SPACING 2
#define SCORE_LABEL_WIDTH 32
#define SCORE_LABEL_HEIGHT 16
#define REMAINING_LABEL_WIDTH SCORE_LABEL_WIDTH
#define REMAINING_LABEL_HEIGHT SCORE_LABEL_HEIGHT
#define LIFE_ICON_WIDTH 16
#define LIFE_ICON_HEIGHT 16
#define LIFE_MAX_WIDTH 40
#define DIGIT_WIDTH 12
#define DIGIT_HEIGHT FONT_NUMBERS_HEIGHT
#define SEMICOLON_WIDTH 6
#define DIGIT_PADDING_TOP ((SCORE_LABEL_HEIGHT - DIGIT_HEIGHT) / 2)
#define TIME_WIDTH (DIGIT_WIDTH + SEMICOLON_WIDTH + DIGIT_WIDTH + DIGIT_WIDTH)

#define TEXT_BUBBLE_HEIGHT 80

#define ZINDEX_BG 0
#define ZINDEX_BG_GRID 9
#define ZINDEX_BONUS 10
#define ZINDEX_ENEMIES 12
#define ZINDEX_PLAYER 13
#define ZINDEX_CAUGHT 14
#define ZINDEX_HANDS 15
#define ZINDEX_EXPLOSIONS 16
#define ZINDEX_CHAIN 16
#define ZINDEX_BULLETS 17
#define ZINDEX_GUI 20
#define ZINDEX_HISCORE 21
#define ZINDEX_FADE 30

#define ADAPT_CRANK(value) (value * 30.0f / REFRESH_RATE)
#define ADAPT_SPEED(value) (REFRESH_RATE * value / 30.0f)

extern PlaydateAPI * _Nullable playdate;
extern LCDFont * _Nullable numbersFont;
extern LCDFont * _Nullable numbers32Font;
extern LCDFont * _Nullable romajiFont;
extern LCDFont * _Nullable rains2xFont;
extern LCDFont * _Nullable nontendoLightFont;
extern int REFRESH_RATE;
extern float DELTA;

#endif /* common_h */
