//
//  ducktool.c
//
//  Generated by Melia on 30/07/2023.
//

#include "ducktool.h"

#include "shootingstyle.h"
#include "aimedshootingstyle.h"
#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spriteducktool.h"
#include "../gen/spritebullet.h"

enum ducktool_state {
    main,
    withdrawing,
};

struct ducktool {
    MELSprite super;

    enum ducktool_state state;
    uint8_t statePart;
    float strideDecimalFrom0;
    ShootingStyle style;
    float time;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct ducktool * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass DucktoolClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

static const ShootingStyleDefinition kStyleDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletDefinition = &spriteBullet,
    .shootInterval = 1.5f,
    .bulletAmount = 1,
    .bulletSpeed = 90.0f,
    .damage = ENEMY_DUCKTOOL_BULLET_DAMAGE,
    .translation = {
        .x = 1.0f,
        .y = -10.0f
    },
};

LCDSprite * _Nonnull DucktoolConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct ducktool *self = playdate->system->realloc(NULL, sizeof(struct ducktool));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &DucktoolClass;
    self->super.hitPoints = ENEMY_DUCKTOOL_HIT_POINTS;
    self->super.score = ENEMY_DUCKTOOL_SCORE;
    self->super.frame.origin.x = 442.0f;
    loadSpriteBulletPalette();
    AimedShootingStyleInit(&self->style, &kStyleDefinition);
    self->super.direction = self->super.instance->center.y < 120 ? MELDirectionDown : MELDirectionUp;
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct ducktool *self = (struct ducktool *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalFrom0);
    ShootingStyleSave(&self->style, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct ducktool *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &DucktoolClass) {
        playdate->system->error("Given sprite is not an instance of Ducktool");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

MELSprite * _Nullable DucktoolLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct ducktool *self = playdate->system->realloc(NULL, sizeof(struct ducktool));
    const enum ducktool_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float strideDecimalFrom0 = MELInputStreamReadFloat(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kStyleDefinition);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct ducktool) {
        .super = {
            .class = &DucktoolClass
        },
        .state = state,
        .statePart = statePart,
        .strideDecimalFrom0 = strideDecimalFrom0,
        .style = style,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct ducktool * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct ducktool *self = playdate->sprite->getUserdata(sprite);

    // during
    self->strideDecimalFrom0 = self->super.instance->center.y - MELDirectionValues[self->super.direction] * 240;
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct ducktool *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = self->strideDecimalFrom0 + (self->super.instance->center.y - self->strideDecimalFrom0) * progress;
        self->super.frame.origin.x = self->super.instance->center.x + 64 + -64 * (progress * progress);
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // while
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);
    mainStatePart2(sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct ducktool *self = playdate->sprite->getUserdata(sprite);

    // while
    // shoot
    ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct ducktool *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct ducktool *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + (442.0f - self->super.instance->center.x) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

