//
//  gunbee.c
//
//  Generated by Melia on 24/05/2023.
//

#include "gunbee.h"

#include "shootingstyle.h"
#include "simpleshootingstyle.h"
#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spritegunbee.h"
#include "../gen/spritebullet.h"

enum gunbee_state {
    main,
    withdrawing,
};

struct gunbee {
    MELSprite super;

    enum gunbee_state state;
    uint8_t statePart;
    float strideDecimalFrom0;
    float strideDecimalTo0;
    ShootingStyle style;
    ShootingStyle style2;
    float time;
    float wobble;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);
static void mainStatePart3(LCDSprite * _Nonnull sprite);
static void mainStatePart4(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct gunbee * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass GunbeeClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

static const ShootingStyleDefinition kLeftStyle = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletSpeed = 100.0f,
    .bulletDefinition = &spriteBullet,
    .bulletAnimationName = AnimationNameRun,
    .bulletAmount = 1,
    .damage = ENEMY_GUNBEE_BULLET_DAMAGE,
    .shootInterval = 0.2f,
    .translation = {
        .x = 20.0f,
        .y = 16.0f
    },
};
static const ShootingStyleDefinition kRightStyle = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletSpeed = 100.0f,
    .bulletDefinition = &spriteBullet,
    .bulletAnimationName = AnimationNameRun,
    .bulletAmount = 1,
    .damage = ENEMY_GUNBEE_BULLET_DAMAGE,
    .shootInterval = 0.2f,
    .translation = {
        .x = 0.0f,
        .y = 8.0f
    },
};

LCDSprite * _Nonnull GunbeeConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct gunbee *self = playdate->system->realloc(NULL, sizeof(struct gunbee));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &GunbeeClass;
    self->super.hitPoints = ENEMY_GUNBEE_HIT_POINTS;
    self->super.score = ENEMY_GUNBEE_SCORE;
    self->super.frame.origin.x = 448.0f;
    self->wobble = 0;
    loadSpriteBulletPalette();
    SimpleShootingStyleInit(&self->style, &kLeftStyle);
    SimpleShootingStyleInit(&self->style2, &kRightStyle);
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct gunbee *self = (struct gunbee *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalFrom0);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalTo0);
    ShootingStyleSave(&self->style, outputStream);
    ShootingStyleSave(&self->style2, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->time);
    MELOutputStreamWriteFloat(outputStream, self->wobble);
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &GunbeeClass) {
        playdate->system->error("Given sprite is not an instance of Gunbee");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

MELSprite * _Nullable GunbeeLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct gunbee *self = playdate->system->realloc(NULL, sizeof(struct gunbee));
    const enum gunbee_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float strideDecimalFrom0 = MELInputStreamReadFloat(inputStream);
    const float strideDecimalTo0 = MELInputStreamReadFloat(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kLeftStyle);
    const ShootingStyle style2 = ShootingStyleLoad(inputStream, &kRightStyle);
    const float time = MELInputStreamReadFloat(inputStream);
    const float wobble = MELInputStreamReadFloat(inputStream);

    *self = (struct gunbee) {
        .super = {
            .class = &GunbeeClass
        },
        .state = state,
        .statePart = statePart,
        .strideDecimalFrom0 = strideDecimalFrom0,
        .strideDecimalTo0 = strideDecimalTo0,
        .style = style,
        .style2 = style2,
        .time = time,
        .wobble = wobble,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct gunbee * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart4);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    self->strideDecimalTo0 = self->super.instance->center.x + cosf(self->wobble) * 16;
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 448.0f + (self->strideDecimalTo0 - 448.0f) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        self->super.frame.origin = (MELPoint) {
            .x = self->super.instance->center.x + cosf(self->wobble) * 16 /* diameter */,
            .y = self->super.instance->center.y + sinf(self->wobble) * 16 /* diameter */
        };
        self->wobble = self->wobble + (DELTA * MELDirectionValues[self->super.direction]) * 2;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart3);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart3(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 3.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
        // shoot
        ShootingStyleShootFromSprite(&self->style2, &self->super, MEL_PI);
        self->super.frame.origin = (MELPoint) {
            .x = self->super.instance->center.x + cosf(self->wobble) * 16 /* diameter */,
            .y = self->super.instance->center.y + sinf(self->wobble) * 16 /* diameter */
        };
        self->wobble = self->wobble + DELTA * MELDirectionValues[self->super.direction];
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart4);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart4(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        self->super.frame.origin = (MELPoint) {
            .x = self->super.instance->center.x + cosf(self->wobble) * 16 /* diameter */,
            .y = self->super.instance->center.y + sinf(self->wobble) * 16 /* diameter */
        };
        self->wobble = self->wobble + DELTA * MELDirectionValues[self->super.direction];
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    self->state = withdrawing;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    self->strideDecimalFrom0 = self->super.frame.origin.x;
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct gunbee *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->strideDecimalFrom0 + (448.0f - self->strideDecimalFrom0) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}
