//
//  gunner_bot.c
//  Kuroobi
//
//  Generated by Melia on 29/10/2023.
//

#include "gunner_bot.h"

#include "camera.h"
#include "aimedshootingstyle.h"
#include "circularshootingstyle.h"
#include "particuleshootingstyle.h"
#include "gui_lives.h"
#include "gamescene.h"
#include "samples.h"
#include "explosion.h"
#include "bonus.h"

#include "../gen/spritenames.h"
#include "../gen/spritegunnerbot.h"
#include "../gen/spritebullet.h"
#include "../gen/spriterocketsmoke.h"
#include "../gen/spritebigexplosion.h"

enum gunner_bot_state {
    main,
    circle,
    zigzag,
    roam,
    enter,
    goBackToMain,
    caught,
    thrown,
    destroyed,
    exploding,
};

struct gunner_bot {
    MELSprite super;

    enum gunner_bot_state state;
    uint8_t statePart;
    int8_t lives;
    int32_t action;
    ShootingStyle aimed;
    ShootingStyle style;
    ShootingStyle smoke;
    MELPoint stridePointFrom0;
    float time;
    MELBoolean wasHit;

    // Attrapé
    /**
     * Centre des mains de Katsuo quand le boss est attrapé.
     */
    MELPoint * _Nullable parentOrigin;
    /**
     * Distance du robot par rapport au centre des mains quand attrapé.
     */
    float distance;
    MELBoolean isCranking;
    MELBoolean shouldThrow;
    float maxCrankChange;

    // Lancé
    float angle;
    float speed;

    // Explosion
    LCDSprite * _Nullable explosion;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);

static void circleStatePart0(LCDSprite * _Nonnull sprite);
static void circleStatePart1(LCDSprite * _Nonnull sprite);
static void circleStatePart2(LCDSprite * _Nonnull sprite);
static void circleStatePart3(LCDSprite * _Nonnull sprite);
static void circleStatePart4(LCDSprite * _Nonnull sprite);
static void circleStatePart5(LCDSprite * _Nonnull sprite);
static void circleStatePart6(LCDSprite * _Nonnull sprite);
static void circleStatePart7(LCDSprite * _Nonnull sprite);

static void zigzagStatePart0(LCDSprite * _Nonnull sprite);
static void zigzagStatePart1(LCDSprite * _Nonnull sprite);
static void zigzagStatePart2(LCDSprite * _Nonnull sprite);
static void zigzagStatePart3(LCDSprite * _Nonnull sprite);
static void zigzagStatePart4(LCDSprite * _Nonnull sprite);
static void zigzagStatePart5(LCDSprite * _Nonnull sprite);
static void zigzagStatePart6(LCDSprite * _Nonnull sprite);
static void zigzagStatePart7(LCDSprite * _Nonnull sprite);
static void zigzagStatePart8(LCDSprite * _Nonnull sprite);
static void zigzagStatePart9(LCDSprite * _Nonnull sprite);
static void zigzagStatePart10(LCDSprite * _Nonnull sprite);
static void zigzagStatePart11(LCDSprite * _Nonnull sprite);

static void roamStatePart0(LCDSprite * _Nonnull sprite);
static void roamStatePart1(LCDSprite * _Nonnull sprite);
static void roamStatePart2(LCDSprite * _Nonnull sprite);
static void roamStatePart3(LCDSprite * _Nonnull sprite);
static void roamStatePart4(LCDSprite * _Nonnull sprite);
static void roamStatePart5(LCDSprite * _Nonnull sprite);
static void roamStatePart6(LCDSprite * _Nonnull sprite);

static void destroyedStatePart0(LCDSprite * _Nonnull sprite);
static void destroyedStatePart1(LCDSprite * _Nonnull sprite);

static void explodingStatePart0(LCDSprite * _Nonnull sprite);

static void goBackToMainStatePart0(LCDSprite * _Nonnull sprite);
static void enterStatePart0(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static void spriteWasHit(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite);
static void updateCaught(LCDSprite * _Nonnull sprite);
static void updateThrown(LCDSprite * _Nonnull sprite);
static void checkCollisionsWithOtherSprites(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite);

static const MELSpriteClass GunnerBotClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
};

static const float kMinimumThrowSpeed = 100.0f;

static MELSpriteInstance kInstance = (MELSpriteInstance) {
    .name = SpriteNameGunnerBot,
    .center = {
        .x = 287,
        .y = 128
    }
};

static const ShootingStyleDefinition kAimedDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletDefinition = &spriteBullet,
    .shootInterval = 0.33333333f,
    .bulletAmount = 1,
    .bulletSpeed = 75.0f,
    .damage = BOSS_GUNNER_BULLET_DAMAGE,
    .translation = {
        .x = 19.0f,
        .y = 8.0f
    },
};

static CircularShootingStyleDefinition kCircularDefinition = (CircularShootingStyleDefinition) {
    .super = {
        .origin = ShotOriginFront,
        .bulletDefinition = &spriteBullet,
        .shootInterval = 0.2f,
        .bulletAmount = 3,
        .bulletSpeed = 50.0f,
        .bulletAnimationName = AnimationNameRun,
        .damage = BOSS_GUNNER_BULLET_DAMAGE,
        .translation = {
            .x = 19.0f,
            .y = 8.0f
        },
    },
    .baseAngle = -MEL_PI / 32.0f,
    .angleIncrement = MEL_PI / 32.0f,
};

static const ShootingStyleDefinition kSmokeDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginCenter,
    .bulletDefinition = &spriteRocketSmoke,
    .bulletAmount = 1,
    .shootInterval = 0.1f,
    .space = 96.0f,
};

LCDSprite * _Nonnull GunnerBotConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct gunner_bot *self = playdate->system->realloc(NULL, sizeof(struct gunner_bot));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &GunnerBotClass;
    self->super.hitPoints = INT32_MAX;
    self->super.score = BOSS_GUNNER_SCORE;
    self->lives = BOSS_GUNNER_HIT_POINTS;
    self->explosion = NULL;
    loadSpriteRocketSmokePalette();
    loadSpriteBulletPalette();
    AimedShootingStyleInit(&self->aimed, &kAimedDefinition);
    CircularShootingStyleInit(&self->style, &kCircularDefinition);
    ParticuleShootingStyleInit(&self->smoke, &kSmokeDefinition);
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);

    GUILivesConstructorWithImagePathAndTopLeft(&self->lives, "gui-teki", (MELPoint) {
        .x = LCD_COLUMNS - REMAINING_LABEL_WIDTH - GUI_PADDING - TIME_WIDTH - GUI_PADDING,
        .y = GUI_PADDING + SCORE_LABEL_HEIGHT + GUI_PADDING 
    });
    return sprite;
}

LCDSprite * _Nonnull GunnerBotConstructorWithOrigin(MELPoint origin) {
    loadSpriteGunnerBotPalette();
    LCDSprite *sprite = GunnerBotConstructor(&spriteGunnerBot, &kInstance);
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    self->super.definition.type = MELSpriteTypeDestructible;
    self->super.frame.origin = origin;
    self->super.hitTimer = 3.0f;
    self->stridePointFrom0 = origin;
    self->state = enter;
    self->statePart = 0;
    self->lives = 1;
    self->time = 0.0f;
    MELSpriteSetAnimation(&self->super, AnimationNameBounce);
    playdate->sprite->setUpdateFunction(sprite, enterStatePart0);

#if LOG_SPRITE_PUSH_AND_REMOVE_FROM_SCENE_SPRITES
    playdate->system->logToConsole("Push GunnerBotConstructorWithOrigin(%x, %x): %d", sprite, self, self->super.definition.name);
#endif
    LCDSpriteRefListPush(&currentScene->sprites, sprite);

    return sprite;
}

void GunnerBotCatch(LCDSprite * _Nonnull sprite, Player * _Nonnull player) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);
    MELSprite *parent = &player->hands->super;

    self->super.definition.type = MELSpriteTypeDestructible;
    self->state = caught;
    self->parentOrigin = &parent->frame.origin;
    self->distance = MELPointDistanceToPoint(parent->frame.origin, self->super.frame.origin);
    self->isCranking = false;
    self->shouldThrow = false;
    self->time = 0.0f;

    playdate->sprite->setZIndex(sprite, ZINDEX_CAUGHT);
    playdate->sprite->setUpdateFunction(sprite, updateCaught);
}

void GunnerBotThrow(LCDSprite * _Nonnull sprite, float angle, float speed, MELBoolean wasHit) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);
    self->wasHit = false;
    if (wasHit) {
        spriteWasHit(self, sprite);
        if (self->lives <= 0) {
            return;
        }
    }

    self->super.definition.type = MELSpriteTypeDestructible;
    self->state = thrown;
    self->angle = angle;
    self->speed = MELFloatMax(speed, kMinimumThrowSpeed);
    self->time = 0.0f;
    MELSpriteSetAnimation(&self->super, AnimationNameBounce);
    self->super.animation->speed = 0.25f + 0.75f * speed / 250.0f;

    playdate->sprite->setUserdata(sprite, self);
    playdate->sprite->setUpdateFunction(sprite, updateThrown);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct gunner_bot *self = (struct gunner_bot *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteByte(outputStream, self->lives);
    MELOutputStreamWriteInt(outputStream, self->action);
    ShootingStyleSave(&self->aimed, outputStream);
    ShootingStyleSave(&self->style, outputStream);
    ShootingStyleSave(&self->smoke, outputStream);
    MELOutputStreamWritePoint(outputStream, self->stridePointFrom0);
    MELOutputStreamWriteFloat(outputStream, self->time);
    MELOutputStreamWriteBoolean(outputStream, self->wasHit);
    MELOutputStreamWriteFloat(outputStream, self->distance);
    MELOutputStreamWriteBoolean(outputStream, self->isCranking);
    MELOutputStreamWriteBoolean(outputStream, self->shouldThrow);
    MELOutputStreamWriteFloat(outputStream, self->maxCrankChange);
    MELOutputStreamWriteFloat(outputStream, self->angle);
    MELOutputStreamWriteFloat(outputStream, self->speed);

    MELOutputStreamWriteBoolean(outputStream, self->explosion != NULL);
    if (self->explosion) {
        MELSprite *explosion = playdate->sprite->getUserdata(self->explosion);
        MELOutputStreamWritePoint(outputStream, explosion->frame.origin);
        MELOutputStreamWriteUInt32(outputStream, explosion->animation->frameIndex);
    }
}

MELSprite * _Nullable GunnerBotLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct gunner_bot *self = playdate->system->realloc(NULL, sizeof(struct gunner_bot));
    const enum gunner_bot_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const int8_t lives = MELInputStreamReadByte(inputStream);
    const int32_t action = MELInputStreamReadInt(inputStream);
    loadSpriteBulletPalette();
    loadSpriteRocketSmokePalette();
    const ShootingStyle aimed = ShootingStyleLoad(inputStream, &kAimedDefinition);
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kCircularDefinition.super);
    const ShootingStyle smoke = ShootingStyleLoad(inputStream, &kSmokeDefinition);
    const MELPoint stridePointFrom0 = MELInputStreamReadPoint(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);
    const MELBoolean wasHit = MELInputStreamReadBoolean(inputStream);
    const float distance = MELInputStreamReadFloat(inputStream);
    const MELBoolean isCranking = MELInputStreamReadBoolean(inputStream);
    const MELBoolean shouldThrow = MELInputStreamReadBoolean(inputStream);
    const float maxCrankChange = MELInputStreamReadFloat(inputStream);
    const float angle = MELInputStreamReadFloat(inputStream);
    const float speed = MELInputStreamReadFloat(inputStream);
    const MELBoolean isExploding = MELInputStreamReadBoolean(inputStream);

    *self = (struct gunner_bot) {
        .super = {
            .class = &GunnerBotClass,
            .instance = &kInstance,
        },
        .state = state,
        .statePart = statePart,
        .lives = lives,
        .action = action,
        .aimed = aimed,
        .style = style,
        .smoke = smoke,
        .stridePointFrom0 = stridePointFrom0,
        .time = time,
        .wasHit = wasHit,
        .distance = distance,
        .isCranking = isCranking,
        .shouldThrow = shouldThrow,
        .maxCrankChange = maxCrankChange,
        .angle = angle,
        .speed = speed,
    };
    if (state == caught) {
        GameScene *gameScene = GameSceneGetCurrent();
        Player *player = gameScene->player;
        MELSprite *parent = &player->hands->super;
        self->parentOrigin = &parent->frame.origin;
    }
    if (isExploding) {
        loadSpriteBigExplosionPalette();
        MELPoint origin = MELInputStreamReadPoint(inputStream);
        LCDSprite *explosionSprite = ExplosionConstructor(origin);
        self->explosion = explosionSprite;
        MELSprite *explosion = playdate->sprite->getUserdata(explosionSprite);

        const uint32_t frameIndex = MELInputStreamReadUInt32(inputStream);
        MELAnimationSetFrameIndex(explosion->animation, frameIndex);
    }
    GUILivesConstructorWithImagePathAndTopLeft(&self->lives, "gui-teki", (MELPoint) {
        .x = LCD_COLUMNS - REMAINING_LABEL_WIDTH - GUI_PADDING - TIME_WIDTH - GUI_PADDING,
        .y = GUI_PADDING + SCORE_LABEL_HEIGHT + GUI_PADDING 
    });
    goToCurrentState(self, sprite);
    return &self->super;
}

static void draw(MELSprite * _Nonnull self, LCDSprite * _Nonnull sprite) {
    MELSpriteDraw(self, sprite);
    camera.frame.origin.x += CAMERA_SPEED_UP_DURING_BOSS_GUNNER * DELTA;
}

static void goToCurrentState(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case circle:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart4);
                    break;
                case 5:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart5);
                    break;
                case 6:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart6);
                    break;
                case 7:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart7);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, circleStatePart0);
                    break;
            }
            break;
        case zigzag:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart4);
                    break;
                case 5:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart5);
                    break;
                case 6:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart6);
                    break;
                case 7:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart7);
                    break;
                case 8:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart8);
                    break;
                case 9:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart9);
                    break;
                case 10:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart10);
                    break;
                case 11:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart11);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, zigzagStatePart0);
                    break;
            }
            break;
        case roam:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart4);
                    break;
                case 5:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart5);
                    break;
                case 6:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart6);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, roamStatePart0);
                    break;
            }
            break;
        case goBackToMain:
            playdate->sprite->setUpdateFunction(sprite, goBackToMainStatePart0);
            break;
        case enter:
            playdate->sprite->setUpdateFunction(sprite, enterStatePart0);
            break;
        case caught:
            playdate->sprite->setUpdateFunction(sprite, updateCaught);
            break;
        case thrown:
            playdate->sprite->setUpdateFunction(sprite, updateThrown);
            break;
        case destroyed:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, destroyedStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, destroyedStatePart0);
                    break;
            }
            break;
        case exploding:
            playdate->sprite->setUpdateFunction(sprite, explodingStatePart0);
            break;
        case main:
            playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
            break;
        
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    switch (MELRandomInt(25)) {
    case 0 ... 9:
        self->state = circle;
        break;
    case 10 ... 19:
        self->state = zigzag;
        break;
    case 20 ... 24:
        self->state = roam;
        break;
    }
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(&self->super, sprite);
}

static void circleStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    kCircularDefinition.angleIncrement = 0.098174766f;
    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart1);

    draw(&self->super, sprite);
}

static void circleStatePart1(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + (370 - self->super.instance->center.x) * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart2);

    draw(&self->super, sprite);
}

static void circleStatePart2(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 10.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin = (MELPoint) {
            .x = 400 /* screenWidth */ / 2 + cosf((progress * 2) * 3.1415925f) * (370 /* ovalX */ - 400 /* screenWidth */ / 2),
            .y = self->super.instance->center.y - sinf((progress * 2) * 3.1415925f) * 80 /* ovalY */
        };
        // shoot
        ShootingStyleShootFromSprite(&self->aimed, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart3);

    draw(&self->super, sprite);
}

static void circleStatePart3(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 370 + (self->super.instance->center.x - 370) * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart4);

    draw(&self->super, sprite);
}

static void circleStatePart4(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    const int bulletAmount = self->style.bulletAmount = 15;
    self->style.baseAngle = 0;
    kCircularDefinition.angleIncrement = 2.0f * MEL_PI / bulletAmount;
    // during
    self->time = 0;
    self->statePart = 5;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart5);

    draw(&self->super, sprite);
}

static void circleStatePart5(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->style.baseAngle = 0 + 1.5707963f * progress;
        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 6;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart6);

    draw(&self->super, sprite);
}

static void circleStatePart6(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 7;
    playdate->sprite->setUpdateFunction(sprite, &circleStatePart7);

    draw(&self->super, sprite);
}

static void circleStatePart7(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x;
        draw(&self->super, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(&self->super, sprite);
}

static void zigzagStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart1);

    draw(&self->super, sprite);
}

static void zigzagStatePart1(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + 20 * progress;
        self->super.frame.origin.y = self->super.instance->center.y - 60 * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart2);

    draw(&self->super, sprite);
}

static void zigzagStatePart2(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // shoot
        ShootingStyleShootFromSprite(&self->aimed, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart3);

    draw(&self->super, sprite);
}

static void zigzagStatePart3(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + 20 + 20 * progress;
        self->super.frame.origin.y = self->super.instance->center.y - 60 + 120 * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart4);

    draw(&self->super, sprite);
}

static void zigzagStatePart4(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // shoot
        ShootingStyleShootFromSprite(&self->aimed, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 5;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart5);

    draw(&self->super, sprite);
}

static void zigzagStatePart5(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + 40 + 20 * progress;
        self->super.frame.origin.y = self->super.instance->center.y + 60 + -120 * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 6;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart6);

    draw(&self->super, sprite);
}

static void zigzagStatePart6(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // shoot
        ShootingStyleShootFromSprite(&self->aimed, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 7;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart7);

    draw(&self->super, sprite);
}

static void zigzagStatePart7(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + 60 + (200 - (self->super.instance->center.x + 60)) * progress;
        self->super.frame.origin.y = self->super.instance->center.y - 60 + 60 * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 8;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart8);

    draw(&self->super, sprite);
}

static void zigzagStatePart8(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    kCircularDefinition.angleIncrement = 0.098174766f;
    self->style.bulletAmount = 2;
    // during
    self->time = 0;
    self->statePart = 9;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart9);

    draw(&self->super, sprite);
}

static void zigzagStatePart9(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 6.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = newTime / duration;
        self->time = newTime;

        self->style.baseAngle = 1.5707963f + -6.283185f * progress;
        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 10;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart10);

    draw(&self->super, sprite);
}

static void zigzagStatePart10(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 200 + (self->super.instance->center.x - 200) * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 11;
    playdate->sprite->setUpdateFunction(sprite, &zigzagStatePart11);

    draw(&self->super, sprite);
}

static void zigzagStatePart11(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(&self->super, sprite);
}

static void roamStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &roamStatePart1);

    draw(&self->super, sprite);
}

static void roamStatePart1(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + (448.0f - self->super.instance->center.x) * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &roamStatePart2);

    draw(&self->super, sprite);
}

static void roamStatePart2(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    const int bulletAmount = self->style.bulletAmount = 10;
    self->style.baseAngle = 0;
    kCircularDefinition.angleIncrement = 2.0f * MEL_PI / bulletAmount;
    // during
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &roamStatePart3);

    draw(&self->super, sprite);
}

static void roamStatePart3(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 448.0f + -496.0f * progress;
        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &roamStatePart4);

    draw(&self->super, sprite);
}

static void roamStatePart4(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 5;
    playdate->sprite->setUpdateFunction(sprite, &roamStatePart5);

    draw(&self->super, sprite);
}

static void roamStatePart5(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = -48.0f + (self->super.instance->center.x - -48.0f) * progress;
        draw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 6;
    playdate->sprite->setUpdateFunction(sprite, &roamStatePart6);

    draw(&self->super, sprite);
}

static void roamStatePart6(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(&self->super, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(&self->super, sprite);
}

static void goBackToMainStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = self->time = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);

        self->super.frame.origin = MELPointAdd(self->stridePointFrom0, MELPointMultiplyByValue((MELPointSubstract(self->super.instance->center, self->stridePointFrom0)), progress));
        draw(&self->super, sprite);
        return;
    }
    self->super.definition.type = MELSpriteTypeCollidable;
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(&self->super, sprite);
}

#pragma mark - Arrivée en jeu

static void enterStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 3.0f;
    if (self->time < duration) {
        const float newTime = self->time = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);

        // Rempli la barre de vie en affichant une vie chaque 0,25s.
        self->lives = MELIntBound(1, newTime / 0.25f, BOSS_GUNNER_HIT_POINTS);

        self->super.frame.origin = MELPointAdd(self->stridePointFrom0, MELPointMultiplyByValue((MELPointSubstract(self->super.instance->center, self->stridePointFrom0)), progress));
        draw(&self->super, sprite);
        return;
    }
    MELSpriteSetAnimation(&self->super, AnimationNameStand);
    self->lives = BOSS_GUNNER_HIT_POINTS;
    self->super.definition.type = MELSpriteTypeCollidable;
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(&self->super, sprite);
}


#pragma mark - Touché

static void spriteWasHit(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite) {
    if (!self->wasHit) {
        self->wasHit = true;
        self->super.hitTimer = 3.5f;
        const int8_t lives = --self->lives;
        SamplePlay(SampleCollision);

        if (lives <= 0) {
            self->state = destroyed;
            self->statePart = 0;
            playdate->sprite->setUpdateFunction(sprite, destroyedStatePart0);
        }
    }
}

#pragma mark - Attrapé

static const float kMinimumSpeedToThrow = 10.0f;
static const float kMinimumMovement = 5.0f;
static const float kSpeedMultiplier = 16.0f;
static const float kMaximumThrowSpeed = 50.0f;

static void restoreState(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite) {
    self->time = 0;
    self->state = goBackToMain;
    self->statePart = 0;
    self->stridePointFrom0 = self->super.frame.origin;
    MELSpriteSetAnimation(&self->super, AnimationNameStand);
    goToCurrentState(self, sprite);
}

static void updateCaught(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);
    const MELPoint parentOrigin = *self->parentOrigin;
    GameScene *gameScene = GameSceneGetCurrent();
    Player *player = gameScene->player;
    if (!player->isCatching) {
        restoreState(self, sprite);
        return;
    }

    const float crankAngle = playdate->system->getCrankAngle() - FORWARD_ANGLE + 360.0f;
    const float radian = MELDegreesToRadians(crankAngle);
    MELPoint origin = (MELPoint) {
        .x = parentOrigin.x + self->distance * cosf(radian),
        .y = parentOrigin.y + self->distance * sinf(radian),
    };

    const float duration = 2.5f;
    if (self->time < duration) {
        const float newTime = self->time = MELFloatMin(self->time + DELTA, duration);
        if (newTime >= 0.0f && newTime < 1.0f) {
            const float progress = MELEaseInOut(0.0f, 1.0f, newTime);
            origin.y += 2 * sinf(50.26548f * progress);
        } else if (newTime >= 1.5f && newTime < 2.5f) {
            const float progress = MELEaseInOut(1.25f, 2.25f, newTime);
            origin.x += 2 * sinf(50.26548f * progress);
        }
    } else {
        self->time -= duration;
    }

    self->super.frame.origin = origin;

    checkCollisionsWithOtherSprites(self, sprite);

    const MELBoolean isCranking = self->isCranking;
    const float crankChange = fabsf(MELCrankGetAcceleratedChange());
    if (!isCranking && crankChange != 0.0f) {
#if LOG_CATCHES_AND_THROWS
        playdate->system->logToConsole("Started cranking, crankChange: %f", (double) crankChange);
#endif
        self->isCranking = true;
        self->maxCrankChange = 0.0f;
    } else if (isCranking && (self->maxCrankChange < ADAPT_CRANK(kMinimumSpeedToThrow) || crankChange > ADAPT_CRANK(kMinimumMovement))) {
#if LOG_CATCHES_AND_THROWS
        playdate->system->logToConsole("Cranking! max: %f, crankChange: %f", (double) self->maxCrankChange, (double) crankChange);
#endif
        if (crankChange > self->maxCrankChange) {
            self->maxCrankChange = crankChange;
        }
    } else if (isCranking) {
        self->isCranking = false;
        const float speed = MELFloatMin(self->maxCrankChange, kMaximumThrowSpeed);
#if LOG_CATCHES_AND_THROWS
        playdate->system->logToConsole("Crank speed slowed down, throwing! max: %f, crankChange: %f", (double) self->maxCrankChange, (double) crankChange);
        playdate->system->logToConsole("speed: %f, total: %f", (double) speed, (double) (speed * ADAPT_SPEED(kSpeedMultiplier)));
#endif
        player->isCatching = false;
        GunnerBotThrow(sprite, radian, speed * ADAPT_SPEED(kSpeedMultiplier), false);

        // Bruit de jet.
        SamplePlay(SampleThrow);
    }

    draw(&self->super, sprite);
}

#pragma mark - Lancé

static void updateThrown(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);
    float angle = self->angle;

    if (self->wasHit) {
        const float hitDuration = 2.0f;
        const float time = self->time += DELTA;
        if (time >= hitDuration) {
            restoreState(self, sprite);
            return;
        }
    }

    MELPoint origin = self->super.frame.origin;
    origin.x += self->speed * DELTA * cosf(angle);
    origin.y += self->speed * DELTA * sinf(angle);

    if (origin.y < 0) {
        origin.y = -origin.y;
        angle = -angle;
        spriteWasHit(self, sprite);
    } else if (origin.y >= LCD_ROWS) {
        origin.y = LCD_ROWS + LCD_ROWS - origin.y;
        angle = -angle;
        spriteWasHit(self, sprite);
    }
    if (origin.x < 0) {
        origin.x = -origin.x;
        angle = MEL_PI - angle;
        spriteWasHit(self, sprite);
    } else if (origin.x >= LCD_COLUMNS) {
        origin.x = LCD_COLUMNS + LCD_COLUMNS - origin.x;
        angle = MEL_PI - angle;
        spriteWasHit(self, sprite);
    }

    self->angle = angle;
    self->super.frame.origin = origin;

    checkCollisionsWithOtherSprites(self, sprite);

   draw(&self->super, sprite);
}

#pragma mark - Gestion des collisions quand lancé ou attrapé

static void checkCollisionsWithOtherSprites(struct gunner_bot * _Nonnull self, LCDSprite * _Nonnull sprite) {
    const MELRectangle selfHitbox = MELHitboxGetFrame(self->super.hitbox);
    // Pas de suppression de sprites dans l'itération donc pas besoin de copier la liste.
    LCDSpriteRefList *otherSprites = &currentScene->sprites;
    for (unsigned int index = 0; index < otherSprites->count; index++) {
        LCDSprite *otherSprite = otherSprites->memory[index];
        MELSprite *other = playdate->sprite->getUserdata(otherSprite);
        switch (other->definition.type) {
            case MELSpriteTypeBullet:
                if (MELHitboxCollidesWithRectangle(other->hitbox, selfHitbox)) {
                    GameSceneScoreAdd(other->hitPoints * BULLET_SCORE_MULTIPLIER, 0);
                    playdate->sprite->setUpdateFunction(otherSprite, other->class->destroy);

                    // Bruit d'arrêt de tir.
                    SamplePlay(SampleBulletCollision);
                }
                break;
            default:
                // Pas de traitement.
                break;
        }
    }
}

#pragma mark - Explosion

static void destroyedStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);
    self->super.definition.type = MELSpriteTypeDecor;
    self->super.hitTimer = 5.0f;

    GameSceneDestroyBullets();
    loadSpriteRocketSmokePalette();

    GameSceneScoreAdd(self->super.score, 0);
    BonusCreate(&self->super, -MEL_PI_2, 100.0f);

    // during
    self->time = 0;
    self->statePart = 1;
    self->stridePointFrom0 = self->super.frame.origin;
    self->maxCrankChange = 0.0f;
    playdate->sprite->setUpdateFunction(sprite, &destroyedStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void destroyedStatePart1(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 5.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        if (newTime - self->maxCrankChange >= 0.5f) {
            SamplePlay(SampleBulletCollision);
            self->maxCrankChange = newTime;
        }

        self->super.frame.origin.x = self->stridePointFrom0.x + 64 + -64 * ((1 - progress) * (1 - progress));
        self->super.frame.origin.y = self->stridePointFrom0.y + 80 * progress;
        self->super.frame.origin.x += ((2 * progress) * cosf(25.13274f * self->time)) * 2;
        self->super.frame.origin.y += ((2 * progress) * sinf(25.13274f * self->time)) * 2;
        // shoot
        ShootingStyleShootFromSprite(&self->smoke, &self->super, 0.0f);
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    loadSpriteBigExplosionPalette();
    LCDSprite *explosion = ExplosionConstructorWithDefinition(self->super.frame.origin, &spriteBigExplosion);
    CameraShakeConstructor(2.0f, 30.0f);

    self->explosion = explosion;
    self->state = exploding;
    self->statePart = 0;
    playdate->sprite->setVisible(sprite, false);
    playdate->sprite->setUpdateFunction(sprite, explodingStatePart0);

    SamplePlay(SampleExplosion);
}

static void explodingStatePart0(LCDSprite * _Nonnull sprite) {
    struct gunner_bot *self = playdate->sprite->getUserdata(sprite);
    MELSprite *explosion = playdate->sprite->getUserdata(self->explosion);
    if (MELAnimationIsLastFrame(explosion->animation)) {
        GameSceneFadeToClearScreen();
        MELSpriteDealloc(sprite);
    }
}

