//
//  jester.h
//
//  Generated by Melia on 04/05/2023.
//

#ifndef jester_h
#define jester_h

#include "common.h"
#include "../lib/melice.h"

LCDSprite * _Nonnull JesterConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance);

MELSprite * _Nullable JesterLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream);

#endif /* jester_h */

