//
//  jester.c
//
//  Generated by Melia on 24/05/2023.
//

#include "jester.h"

#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spritejester.h"

enum jester_state {
    main,
    withdrawing,
};

struct jester {
    MELSprite super;

    enum jester_state state;
    uint8_t statePart;
    MELPoint stridePointFrom0;
    MELPoint stridePointTo0;
    float time;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);
static void mainStatePart3(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct jester * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass JesterClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

LCDSprite * _Nonnull JesterConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct jester *self = playdate->system->realloc(NULL, sizeof(struct jester));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &JesterClass;
    self->super.hitPoints = ENEMY_JESTER_HIT_POINTS;
    self->super.score = ENEMY_JESTER_SCORE;
    self->super.frame.origin = MELPointAdd(self->super.instance->center, MELPointMultiplyByDirection((MELPoint) { .x = 240.0f, .y = -240.0f }, self->super.direction));
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct jester *self = (struct jester *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWritePoint(outputStream, self->stridePointFrom0);
    MELOutputStreamWritePoint(outputStream, self->stridePointTo0);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable JesterLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct jester *self = playdate->system->realloc(NULL, sizeof(struct jester));
    const enum jester_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const MELPoint stridePointFrom0 = MELInputStreamReadPoint(inputStream);
    const MELPoint stridePointTo0 = MELInputStreamReadPoint(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct jester) {
        .super = {
            .class = &JesterClass
        },
        .state = state,
        .statePart = statePart,
        .stridePointFrom0 = stridePointFrom0,
        .stridePointTo0 = stridePointTo0,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct jester * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart3);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &JesterClass) {
        playdate->system->error("Given sprite is not an instance of Jester");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void draw(struct jester * _Nonnull self, LCDSprite * _Nonnull sprite) {
    MELAnimationUpdate(self->super.animation, DELTA);

    const MELPoint origin = self->super.frame.origin;
    playdate->sprite->moveTo(sprite, origin.x, origin.y);
    playdate->sprite->setImage(sprite, playdate->graphics->getTableBitmap(self->super.definition.palette, self->super.animation->frame.atlasIndex), MELDirectionFlip[self->super.direction]);

    MELSpriteChangeDrawModeWhenHit(&self->super, sprite);
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    draw(self, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = self->super.instance->center.x / 200.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        draw(self, sprite);
        return;
    }
    // during
    self->stridePointFrom0 = MELPointAdd(self->super.instance->center, MELPointMultiplyByDirection((MELPoint) { .x = 240.0f, .y = -240.0f }, self->super.direction));
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    draw(self, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin = MELPointAdd(self->stridePointFrom0, MELPointMultiplyByValue((MELPointSubstract(self->super.instance->center, self->stridePointFrom0)), progress));
        draw(self, sprite);
        return;
    }
    // during
    self->stridePointTo0 = MELPointAdd(self->super.instance->center, MELPointMultiplyByDirection((MELPoint) { .x = -16.0f, .y = 16.0f }, self->super.direction));
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart3);

    draw(self, sprite);
}

static void mainStatePart3(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = newTime / duration;
        self->time = newTime;

        self->super.frame.origin = MELPointAdd(self->super.instance->center, MELPointMultiplyByValue((MELPointSubstract(self->stridePointTo0, self->super.instance->center)), progress));
        draw(self, sprite);
        return;
    }
    self->state = withdrawing;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);

    // during
    self->stridePointFrom0 = MELPointAdd(self->super.instance->center, MELPointMultiplyByDirection((MELPoint) { .x = -16.0f, .y = 16.0f }, self->super.direction));
    self->stridePointTo0 = MELPointAdd(self->super.instance->center, MELPointMultiplyByDirection((MELPoint) { .x = -240.0f, .y = 240.0f }, self->super.direction));
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    draw(self, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct jester *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.5f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin = MELPointAdd(self->stridePointFrom0, MELPointMultiplyByValue((MELPointSubstract(self->stridePointTo0, self->stridePointFrom0)), progress));
        draw(self, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

