//
//  magic_ball.c
//
//  Generated by Melia on 13/01/2024.
//

#include "magic_ball.h"

#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spritemagicball.h"
#include "../gen/spritesparks.h"

struct magic_ball {
    MELSprite super;

    MELShootingStyle style;
    MELPoint origin;
    float targetX, variableX;
    float targetY, variableY;
    float time;
    int chips;
    Side side;
    Event event;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct magic_ball * _Nonnull self, LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass MagicBallClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
};

static const MELShootingStyleDefinition kSparksDefinition = (MELShootingStyleDefinition) {
    .bulletDefinition = &spriteSparks,
    .origin = MELShotOriginCenter,
    .shootInterval = 0.05f,
    .bulletAmount = 1,
    .space = 30.0f,
};

LCDSprite * _Nonnull MagicBallConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct magic_ball *self = playdate->system->realloc(NULL, sizeof(struct magic_ball));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &MagicBallClass;
    self->time = 0.0f;
    ParticuleShootingStyleInit(&self->style, &kSparksDefinition);
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    return sprite;
}

static LCDSprite * _Nonnull MagicBallConstructorWithOriginAndTarget(Side side, int chips, MELPoint origin, MELPoint target, float multiplerX, Event event) {
    loadSpriteMagicBallPalette();
    loadSpriteSparksPalette();
    struct magic_ball *self = playdate->system->realloc(NULL, sizeof(struct magic_ball));
    LCDSprite *sprite = MELSpriteInitWithCenter(&self->super, &spriteMagicBall, origin);
    self->super.class = &MagicBallClass;
    self->origin = origin;
    const float variable = 200.0f;
    self->targetX = target.x - origin.x + variable * multiplerX;
    self->variableX = -variable * multiplerX;
    self->targetY = target.y - origin.y + variable;
    self->variableY = -variable;
    self->side = side;
    self->chips = chips;
    self->time = 0.0f;
    self->event = event;
    ParticuleShootingStyleInit(&self->style, &kSparksDefinition);
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_SENDING_CHIP);
    LCDSpriteRefListPush(&currentScene->sprites, sprite);
    return sprite;
}

LCDSprite * _Nonnull MagicBallConstructorAttack(Side side, int chips, MELPoint origin) {
    return MagicBallConstructorWithOriginAndTarget(side, chips, origin, (MELPoint) {
        .x = SideOriginLeft[SideOpposite[side]] + spriteMagicBall.size.width / 2.0f,
        .y = 8,
    }, side == SideLeft ? 1.0f : -1.0f, SideSentChipsEvent[side]);
}

LCDSprite * _Nonnull MagicBallConstructorDefend(Side side, int chips, MELPoint origin) {
    return MagicBallConstructorWithOriginAndTarget(side, -chips, origin, (MELPoint) {
        .x = SideOriginLeft[side] + spriteMagicBall.size.width / 2.0f,
        .y = 8,
    }, side == SideLeft ? 1.0f : -1.0f, SideSentChipsEvent[SideOpposite[side]]);
}

LCDSprite * _Nonnull MagicBallConstructorCounter(Side side, int chips) {
    return MagicBallConstructorWithOriginAndTarget(side, chips, (MELPoint) {
        .x = SideOriginLeft[side] + spriteMagicBall.size.width / 2.0f,
        .y = 8,
    }, (MELPoint) {
        .x = SideOriginLeft[SideOpposite[side]] + spriteMagicBall.size.width / 2.0f,
        .y = 8,
    }, 0.0f, SideSentChipsEvent[side]);
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct magic_ball *self = (struct magic_ball *)sprite;
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable MagicBallLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct magic_ball *self = playdate->system->realloc(NULL, sizeof(struct magic_ball));
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct magic_ball) {
        .super = {
            .class = &MagicBallClass
        },
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct magic_ball * _Nonnull self, LCDSprite * _Nonnull sprite) {
    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct magic_ball *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        // shoot
        MELShootingStyleShootFromSprite(&self->style, &self->super, 0.0f);

        const MELPoint origin = self->origin;
        self->super.frame.origin = (MELPoint) {
            .x = origin.x + self->targetX * progress + self->variableX * progress * progress,
            .y = origin.y + self->targetY * progress + self->variableY * progress * progress,
        };
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELEventBusFireEvent(self->event, self->chips);
    MELSpriteDealloc(sprite);
}
