//
//  mid_boss.c
//
//  Generated by Melia on 05/05/2023.
//

#include "mid_boss.h"

#include "shootingstyle.h"
#include "simpleshootingstyle.h"
#include "rocketshootingstyle.h"
#include "circularshootingstyle.h"
#include "particuleshootingstyle.h"
#include "gui_lifebar.h"
#include "gamescene.h"
#include "explosion.h"
#include "bonus.h"
#include "camera.h"
#include "samples.h"
#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spritemidboss.h"
#include "../gen/spritemidbossaux.h"
#include "../gen/spritebullet.h"
#include "../gen/spritearrow.h"
#include "../gen/spriterocket.h"
#include "../gen/spriterocketsmoke.h"
#include "../gen/spritebigexplosion.h"

enum mid_boss_state {
    entering,
    main,
    protect,
    destroyed,
    exploding,
};

struct mid_boss {
    MELSprite super;
    LCDSprite * _Nullable lifeBar;
    LCDSprite * _Nullable explosion;

    enum mid_boss_state state;
    uint8_t statePart;
    MELSubSprite * _Nullable bottom;
    ShootingStyle bottomStyle;
    ShootingStyle circular;
    ShootingStyle rocket;
    ShootingStyle smoke;
    float strideDecimalFrom0;
    float strideDecimalTo0;
    MELPoint stridePointFrom0;
    MELPoint stridePointFrom1;
    MELPoint stridePointTo0;
    MELPoint stridePointTo1;
    float time;
    MELSubSprite * _Nullable top;
    ShootingStyle topStyle;
    float wobble;
};

static const ShootingStyleDefinition kStyleDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletDefinition = &spriteArrow,
    .bulletAmount = 1,
    .bulletSpeed = 90,
    .shootInterval = 0.5f,
    .translation = {
        .x = 7.0f,
        .y = -10.0f
    },
    .damage = BOSS_MID_AUX_BULLET_DAMAGE,
};
static const ShootingStyleDefinition kRocketDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletDefinition = &spriteRocket,
    .bulletAmount = 1,
    .shootInterval = 5.0f,
    .translation = {
        .x = 10.0f,
        .y = 0.0f
    },
    .damage = BOSS_MID_ROCKET_DAMAGE,
};
static const CircularShootingStyleDefinition kCircularDefinition = (CircularShootingStyleDefinition) {
    .super = {
        .origin = ShotOriginFront,
        .bulletDefinition = &spriteBullet,
        .bulletAmount = 4,
        .bulletSpeed = 80,
        .shootInterval = 1.75f,
        .translation = {
            .x = 10.0f,
            .y = -20.0f
        },
        .damage = BOSS_MID_AUX_BULLET_DAMAGE,
    },
    .angleIncrement = 0.05f
};
static const ShootingStyleDefinition kSmokeDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginCenter,
    .bulletDefinition = &spriteRocketSmoke,
    .bulletAmount = 1,
    .shootInterval = 0.1f,
    .space = 96.0f,
};

static void enteringStatePart0(LCDSprite * _Nonnull sprite);
static void enteringStatePart1(LCDSprite * _Nonnull sprite);

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);
static void mainStatePart3(LCDSprite * _Nonnull sprite);
static void mainStatePart4(LCDSprite * _Nonnull sprite);

static void protectStatePart0(LCDSprite * _Nonnull sprite);
static void protectStatePart1(LCDSprite * _Nonnull sprite);
static void protectStatePart2(LCDSprite * _Nonnull sprite);
static void protectStatePart3(LCDSprite * _Nonnull sprite);

static void destroyedStatePart0(LCDSprite * _Nonnull sprite);
static void destroyedStatePart1(LCDSprite * _Nonnull sprite);

static void explodingStatePart0(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct mid_boss * _Nonnull self, LCDSprite * _Nonnull sprite);
static void destroy(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass MidBossClass = (MELSpriteClass) {
    .destroy = destroy,
    .save = save,
};

LCDSprite * _Nonnull MidBossConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct mid_boss *self = playdate->system->realloc(NULL, sizeof(struct mid_boss));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    self->super.class = &MidBossClass;
    self->super.hitPoints = BOSS_MID_HIT_POINTS;
    self->super.score = BOSS_MID_SCORE;
    self->super.frame.origin.x = 470;
    loadSpriteMidBossAuxPalette();
    self->top = MELSubSpriteAllocAndPush(sprite, &spriteMidBossAux, AnimationNameStand);
    self->top->super.hitPoints = BOSS_MID_AUX_HIT_POINTS;
    self->top->super.score = BOSS_MID_AUX_SCORE;
    self->bottom = MELSubSpriteAllocAndPush(sprite, &spriteMidBossAux, AnimationNameStand);
    self->bottom->super.hitPoints = BOSS_MID_AUX_HIT_POINTS;
    self->bottom->super.score = BOSS_MID_AUX_SCORE;
    self->wobble = 0;
    self->explosion = NULL;
    loadSpriteBulletPalette();
    loadSpriteArrowPalette();
    SimpleShootingStyleInit(&self->topStyle, &kStyleDefinition);
    SimpleShootingStyleInit(&self->bottomStyle, &kStyleDefinition);
    CircularShootingStyleInit(&self->circular, &kCircularDefinition);
    ParticuleShootingStyleInit(&self->smoke, &kSmokeDefinition);
    loadSpriteRocketPalette();
    RocketShootingStyleInit(&self->rocket, &kRocketDefinition);
    self->state = entering;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &enteringStatePart0);

    self->lifeBar = GUILifebarConstructor(BOSS_MID_HIT_POINTS, &self->super.hitPoints);
    return sprite;
}

static void destroy(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    playdate->sprite->setUpdateFunction(self->lifeBar, LCDSpriteDeinit);
    MELSubSpriteDeallocFromParent(self->bottom);
    MELSubSpriteDeallocFromParent(self->top);
    MELSpriteDealloc(sprite);
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct mid_boss *self = (struct mid_boss *)sprite;
    GUILifebarSave(self->lifeBar, outputStream);
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELSubSpriteSave(self->bottom, outputStream);
    ShootingStyleSave(&self->bottomStyle, outputStream);
    ShootingStyleSave(&self->circular, outputStream);
    ShootingStyleSave(&self->rocket, outputStream);
    ShootingStyleSave(&self->smoke, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalFrom0);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalTo0);
    MELOutputStreamWritePoint(outputStream, self->stridePointFrom0);
    MELOutputStreamWritePoint(outputStream, self->stridePointFrom1);
    MELOutputStreamWritePoint(outputStream, self->stridePointTo0);
    MELOutputStreamWritePoint(outputStream, self->stridePointTo1);
    MELOutputStreamWriteFloat(outputStream, self->time);
    MELSubSpriteSave(self->top, outputStream);
    ShootingStyleSave(&self->topStyle, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->wobble);

    MELOutputStreamWriteBoolean(outputStream, self->explosion != NULL);
    if (self->explosion) {
        MELSprite *explosion = playdate->sprite->getUserdata(self->explosion);
        MELOutputStreamWritePoint(outputStream, explosion->frame.origin);
        MELOutputStreamWriteUInt32(outputStream, explosion->animation->frameIndex);
    }
}

MELSprite * _Nullable MidBossLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct mid_boss *self = playdate->system->realloc(NULL, sizeof(struct mid_boss));
    LCDSprite *lifeBar = GUILifebarLoad(inputStream, BOSS_MID_HIT_POINTS, &self->super.hitPoints);
    const enum mid_boss_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    MELSubSprite *bottom = MELSubSpriteLoad(inputStream);
    loadSpriteBulletPalette();
    loadSpriteArrowPalette();
    const ShootingStyle bottomStyle = ShootingStyleLoad(inputStream, &kStyleDefinition);
    const ShootingStyle circular = ShootingStyleLoad(inputStream, &kCircularDefinition.super);
    loadSpriteRocketPalette();
    const ShootingStyle rocket = ShootingStyleLoad(inputStream, &kRocketDefinition);
    loadSpriteRocketSmokePalette();
    const ShootingStyle smoke = ShootingStyleLoad(inputStream, &kSmokeDefinition);
    const float strideDecimalFrom0 = MELInputStreamReadFloat(inputStream);
    const float strideDecimalTo0 = MELInputStreamReadFloat(inputStream);
    const MELPoint stridePointFrom0 = MELInputStreamReadPoint(inputStream);
    const MELPoint stridePointFrom1 = MELInputStreamReadPoint(inputStream);
    const MELPoint stridePointTo0 = MELInputStreamReadPoint(inputStream);
    const MELPoint stridePointTo1 = MELInputStreamReadPoint(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);
    MELSubSprite *top = MELSubSpriteLoad(inputStream);
    const ShootingStyle topStyle = ShootingStyleLoad(inputStream, &kStyleDefinition);
    const float wobble = MELInputStreamReadFloat(inputStream);
    const MELBoolean isExploding = MELInputStreamReadBoolean(inputStream);

    if (top->sprite) {
        LCDSpriteRefListPush(&currentScene->sprites, top->sprite);
    }
    if (bottom->sprite) {
        LCDSpriteRefListPush(&currentScene->sprites, bottom->sprite);
    }

    *self = (struct mid_boss) {
        .super = {
            .class = &MidBossClass
        },
        .lifeBar = lifeBar,
        .state = state,
        .statePart = statePart,
        .bottom = bottom,
        .bottomStyle = bottomStyle,
        .circular = circular,
        .rocket = rocket,
        .smoke = smoke,
        .strideDecimalFrom0 = strideDecimalFrom0,
        .strideDecimalTo0 = strideDecimalTo0,
        .stridePointFrom0 = stridePointFrom0,
        .stridePointFrom1 = stridePointFrom1,
        .stridePointTo0 = stridePointTo0,
        .stridePointTo1 = stridePointTo1,
        .time = time,
        .top = top,
        .topStyle = topStyle,
        .wobble = wobble,
    };
    if (isExploding) {
        loadSpriteBigExplosionPalette();
        MELPoint origin = MELInputStreamReadPoint(inputStream);
        LCDSprite *explosionSprite = ExplosionConstructor(origin);
        self->explosion = explosionSprite;
        MELSprite *explosion = playdate->sprite->getUserdata(explosionSprite);

        const uint32_t frameIndex = MELInputStreamReadUInt32(inputStream);
        MELAnimationSetFrameIndex(explosion->animation, frameIndex);
    }
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct mid_boss * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case main:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart4);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
        case protect:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, protectStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, protectStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, protectStatePart3);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, protectStatePart0);
                    break;
            }
            break;
        case destroyed:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, destroyedStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, destroyedStatePart0);
                    break;
            }
            break;
        case exploding:
            playdate->sprite->setUpdateFunction(sprite, explodingStatePart0);
            break;
        case entering:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, enteringStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, enteringStatePart0);
                    break;
            }
            break;
    }
}

static void draw(struct mid_boss * _Nonnull self, LCDSprite * _Nonnull sprite) {
    if (self->super.hitPoints <= 0) {
        GameScene *gameScene = GameSceneGetCurrent();
        // Arrête le temps pendant l'animation.
        gameScene->wave->type = WaveTypeOther;
        self->state = destroyed;
        self->statePart = 0;
        goToCurrentState(self, sprite);
        return;
    }

    const float delta = DELTA;
    const enum mid_boss_state state = self->state;
    if (state != entering) {
        const float wobble = self->wobble + delta;
        self->wobble = wobble;
        self->super.frame.origin.x = self->super.instance->center.x + sinf(wobble) * 10.0f;
        if (((int) (wobble / MEL_PI) % 3) <= 1) {
            const float cosWobble = cosf(wobble) / 12.0f;
            ShootingStyleShootFromSprite(&self->topStyle, &self->top->super, MEL_PI - cosWobble);
            ShootingStyleShootFromSprite(&self->bottomStyle, &self->bottom->super, MEL_PI + cosWobble);
        } else {
            ShootingStyleShootFromSprite(&self->circular, &self->super, MEL_PI - 0.1f);
        }
        ShootingStyleShootFromSprite(&self->rocket, &self->super, MEL_PI);
    }
    MELAnimationUpdate(self->super.animation, delta);

    const MELPoint origin = self->super.frame.origin;
    playdate->sprite->moveTo(sprite, origin.x, origin.y);
    playdate->sprite->setImage(sprite, playdate->graphics->getTableBitmap(self->super.definition.palette, self->super.animation->frame.atlasIndex), kBitmapUnflipped);
}

static void moveAuxiliariesToTopAndBottom(struct mid_boss * _Nonnull self) {
    const MELPoint origin = self->super.frame.origin;
    self->top->super.frame.origin = (MELPoint) {
        .x = origin.x,
        .y = origin.y - 90.0f * origin.y / 130.0f
    };
    self->bottom->super.frame.origin = (MELPoint) {
        .x = origin.x,
        .y = origin.y + 90.0f * (LCD_ROWS - origin.y) / 130.0f
    };
}

static void enteringStatePart0(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &enteringStatePart1);

    draw(self, sprite);
}

static void enteringStatePart1(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + delta, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 470 + (self->super.instance->center.x - 470) * progress;
        moveAuxiliariesToTopAndBottom(self);
        draw(self, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);

    // while
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);
    mainStatePart1(sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // while
    if (self->super.frame.origin.y > 100) {
        self->super.frame.origin.y = self->super.frame.origin.y - delta * 20;
        moveAuxiliariesToTopAndBottom(self);
        draw(self, sprite);
        return;
    }
    // during
    self->strideDecimalFrom0 = self->super.frame.origin.y;
    self->strideDecimalTo0 = self->super.frame.origin.y - 10;
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    draw(self, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + delta, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = self->strideDecimalFrom0 + (self->strideDecimalTo0 - self->strideDecimalFrom0) * progress;
        moveAuxiliariesToTopAndBottom(self);
        draw(self, sprite);
        return;
    }
    // while
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart3);
    mainStatePart3(sprite);
}

static void mainStatePart3(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // while
    if (self->super.frame.origin.y < 140) {
        self->super.frame.origin.y = self->super.frame.origin.y + delta * 20;
        moveAuxiliariesToTopAndBottom(self);
        draw(self, sprite);
        return;
    }
    // during
    self->strideDecimalFrom0 = self->super.frame.origin.y;
    self->strideDecimalTo0 = self->super.frame.origin.y + 10;
    self->time = 0;
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart4);

    draw(self, sprite);
}

static void mainStatePart4(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + delta, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.y = self->strideDecimalFrom0 + (self->strideDecimalTo0 - self->strideDecimalFrom0) * progress;
        moveAuxiliariesToTopAndBottom(self);
        draw(self, sprite);
        return;
    }
    self->state = protect;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void protectStatePart0(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);

    // during
    self->stridePointFrom0 = self->top->super.frame.origin;
    self->stridePointTo0 = MELPointAdd(self->super.frame.origin, (MELPoint) { .x = -80.0f, .y = -30.0f });
    self->stridePointFrom1 = self->bottom->super.frame.origin;
    self->stridePointTo1 = MELPointAdd(self->super.frame.origin, (MELPoint) { .x = -80.0f, .y = 30.0f });
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &protectStatePart1);

    draw(self, sprite);
}

static void protectStatePart1(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + delta, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->top->super.frame.origin = MELPointAdd(self->stridePointFrom0, MELPointMultiplyByValue((MELPointSubstract(self->stridePointTo0, self->stridePointFrom0)), progress));
        self->bottom->super.frame.origin = MELPointAdd(self->stridePointFrom1, MELPointMultiplyByValue((MELPointSubstract(self->stridePointTo1, self->stridePointFrom1)), progress));
        draw(self, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &protectStatePart2);

    draw(self, sprite);
}

static void protectStatePart2(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // during
    const float duration = 5.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + delta, duration);
        self->time = newTime;

        // wait
        draw(self, sprite);
        return;
    }
    // during
    self->stridePointFrom0 = self->top->super.frame.origin;
    self->stridePointTo0 = MELPointSubstract(self->super.frame.origin, MELPointDivideByValue((MELPointMultiplyByValue((MELPoint) { .x = 0.0f, .y = 90.0f }, self->super.frame.origin.y)), 130.0f));
    self->stridePointFrom1 = self->bottom->super.frame.origin;
    self->stridePointTo1 = MELPointAdd(self->super.frame.origin, MELPointDivideByValue((MELPointMultiplyByValue((MELPoint) { .x = 0.0f, .y = 90.0f }, (240 - self->super.frame.origin.y))), 130.0f));
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &protectStatePart3);

    draw(self, sprite);
}

static void protectStatePart3(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + delta, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->top->super.frame.origin = MELPointAdd(self->stridePointFrom0, MELPointMultiplyByValue((MELPointSubstract(self->stridePointTo0, self->stridePointFrom0)), progress));
        self->bottom->super.frame.origin = MELPointAdd(self->stridePointFrom1, MELPointMultiplyByValue((MELPointSubstract(self->stridePointTo1, self->stridePointFrom1)), progress));
        draw(self, sprite);
        return;
    }
    self->state = main;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    draw(self, sprite);
}

static void destroyedStatePart0(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);

    self->super.definition.type = MELSpriteTypeDecor;
    self->top->super.hitPoints = 0;
    self->bottom->super.hitPoints = 0;
    self->super.hitTimer = 5.0f;

    GameSceneDestroyBullets();
    loadSpriteRocketSmokePalette();

    GameSceneScoreAdd(self->super.score, 0);
    BonusCreate(&self->super, -MEL_PI_2, 100.0f);

    // during
    self->time = 0;
    self->statePart = 1;
    self->stridePointFrom0 = self->super.frame.origin;
    self->strideDecimalFrom0 = 0.0f;
    playdate->sprite->setUpdateFunction(sprite, &destroyedStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void destroyedStatePart1(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 5.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        if (newTime - self->strideDecimalFrom0 >= 0.5f) {
            SamplePlay(SampleBulletCollision);
            self->strideDecimalFrom0 = newTime;
        }

        self->super.frame.origin.x = self->stridePointFrom0.x + 64 + -64 * ((1 - progress) * (1 - progress));
        self->super.frame.origin.y = self->stridePointFrom0.y + 80 * progress;
        self->super.frame.origin.x += ((2 * progress) * cosf(25.13274f * self->time)) * 2;
        self->super.frame.origin.y += ((2 * progress) * sinf(25.13274f * self->time)) * 2;
        // shoot
        ShootingStyleShootFromSprite(&self->smoke, &self->super, 0.0f);
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    loadSpriteBigExplosionPalette();
    LCDSprite *explosion = ExplosionConstructorWithDefinition(self->super.frame.origin, &spriteBigExplosion);
    CameraShakeConstructor(2.0f, 30.0f);

    self->explosion = explosion;
    self->state = exploding;
    self->statePart = 0;
    playdate->sprite->setVisible(sprite, false);
    playdate->sprite->setUpdateFunction(sprite, explodingStatePart0);

    SamplePlay(SampleExplosion);
}

static void explodingStatePart0(LCDSprite * _Nonnull sprite) {
    struct mid_boss *self = playdate->sprite->getUserdata(sprite);
    MELSprite *explosion = playdate->sprite->getUserdata(self->explosion);
    if (MELAnimationIsLastFrame(explosion->animation)) {
        destroy(sprite);
        GameSceneNextWave();
    }
}
