//
//  rapid_fire.c
//
//  Generated by Melia on 24/05/2023.
//

#include "rapid_fire.h"

#include "burstshootingstyle.h"
#include "../gen/spritenames.h"
#include "../gen/spritehawk.h"
#include "../gen/spritebullet.h"

enum rapid_fire_state {
    main,
    withdrawing,
};

struct rapid_fire {
    MELSprite super;

    enum rapid_fire_state state;
    uint8_t statePart;
    ShootingStyle style;
    float time;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);
static void mainStatePart3(LCDSprite * _Nonnull sprite);
static void mainStatePart4(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct rapid_fire * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass RapidFireClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

static const ShootingStyleDefinition kShootingStyleDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletDefinition = &spriteBullet,
    .bulletAnimationName = AnimationNameWalk,
    .bulletSpeed = 200,
    .bulletAmount = 2,
    .damage = ENEMY_RAPID_FIRE_BULLET_DAMAGE,
    .shootInterval = 0.05f,
};

LCDSprite * _Nonnull RapidFireConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct rapid_fire *self = playdate->system->realloc(NULL, sizeof(struct rapid_fire));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &RapidFireClass;
    self->super.hitPoints = ENEMY_RAPID_FIRE_HIT_POINTS;
    self->super.score = ENEMY_RAPID_FIRE_SCORE;
    self->super.frame.origin.y = -48.0f;
    self->state = main;
    self->statePart = 0;
    loadSpriteBulletPalette();
    BurstShootingStyleInit(&self->style, &kShootingStyleDefinition);
    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct rapid_fire *self = (struct rapid_fire *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    ShootingStyleSave(&self->style, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable RapidFireLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct rapid_fire *self = playdate->system->realloc(NULL, sizeof(struct rapid_fire));
    const enum rapid_fire_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kShootingStyleDefinition);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct rapid_fire) {
        .super = {
            .class = &RapidFireClass
        },
        .state = state,
        .statePart = statePart,
        .style = style,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &RapidFireClass) {
        playdate->system->error("Given sprite is not an instance of RapidFire");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void goToCurrentState(struct rapid_fire * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart4);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        if (self->super.direction == MELDirectionUp) {
            self->super.frame.origin.y = -32.0f + (self->super.instance->center.y - -32.0f) * progress;
        } else {
            self->super.frame.origin.y = 272.0f + (self->super.instance->center.y - 272.0f) * progress;
        }
        self->super.frame.origin.x = self->super.instance->center.x + 64.0f * ((1 - progress) * (1 - progress));
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 0.2f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart3);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart3(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = newTime / duration;
        self->time = newTime;

        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
        self->super.frame.origin.x = self->super.instance->center.x + 8.0f * progress;
        // wait
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart4);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart4(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 0.5f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    self->state = withdrawing;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct rapid_fire *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        if (self->super.direction == MELDirectionUp) {
            self->super.frame.origin.y = -32.0f + (self->super.instance->center.y - -32.0f) * (1 - progress);
        } else {
            self->super.frame.origin.y = 272.0f + (self->super.instance->center.y - 272.0f) * (1 - progress);
        }
        self->super.frame.origin.x = self->super.instance->center.x + 8.0f + 56.0f * (progress * progress);
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}
