//
//  rotating.c
//
//  Generated by Melia on 16/02/2023.
//

#include "rotating.h"

#include "aimedshootingstyle.h"
#include "../gen/spritenames.h"
#include "../gen/spriteboat.h"
#include "../gen/spritebullet.h"

struct rotating {
    MELSprite super;

    float angle;
    float ray;
    ShootingStyle shootingStyle;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct rotating * _Nonnull self, LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass RotatingClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
};

static const ShootingStyleDefinition kShootingStyleDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginCenter,
    .bulletDefinition = &spriteBullet,
    .bulletAnimationName = AnimationNameStand,
    .bulletSpeed = 100,
    .bulletAmount = 1,
    .damage = ENEMY_ROTATING_BULLET_DAMAGE,
    .shootInterval = 2.0f,
};

LCDSprite * _Nonnull RotatingConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct rotating *self = playdate->system->realloc(NULL, sizeof(struct rotating));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &RotatingClass;
    self->super.hitPoints = ENEMY_ROTATING_HIT_POINTS;
    self->super.score = ENEMY_ROTATING_SCORE;
    const MELPoint target = instance->center;
    self->ray = sqrtf((LCD_COLUMNS - target.x) * (LCD_COLUMNS - target.x) + (LCD_ROWS / 2.0f - target.y) * (LCD_ROWS / 2.0f - target.y));
    self->angle = MELPointAngleToPoint(target, (MELPoint) { .x = LCD_COLUMNS, .y = LCD_ROWS / 2 }) + MEL_PI;
    self->super.frame.origin.x += LCD_COLUMNS;
    loadSpriteBulletPalette();
    AimedShootingStyleInit(&self->shootingStyle, &kShootingStyleDefinition);
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct rotating *self = (struct rotating *)sprite;
    MELOutputStreamWriteFloat(outputStream, self->angle);
    MELOutputStreamWriteFloat(outputStream, self->ray);
    ShootingStyleSave(&self->shootingStyle, outputStream);
}

MELSprite * _Nullable RotatingLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct rotating *self = playdate->system->realloc(NULL, sizeof(struct rotating));
    const float angle = MELInputStreamReadFloat(inputStream);
    const float ray = MELInputStreamReadFloat(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle shootingStyle = ShootingStyleLoad(inputStream, &kShootingStyleDefinition);

    *self = (struct rotating) {
        .super = {
            .class = &RotatingClass
        },
        .angle = angle,
        .ray = ray,
        .shootingStyle = shootingStyle,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct rotating * _Nonnull self, LCDSprite * _Nonnull sprite) {
    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct rotating *self = playdate->sprite->getUserdata(sprite);
    const float delta = DELTA;

    const float angle = self->angle - MELDirectionValues[self->super.direction] * delta * (MEL_PI / 3.0f);

    if (angle < -3 * MEL_PI - MEL_PI_2) {
        MELSpriteDealloc(sprite);
        return;
    }

    self->angle = angle;
    const MELPoint origin = (MELPoint) {
        .x = cosf(angle) * self->ray + LCD_COLUMNS,
        .y = sinf(angle) * self->ray + LCD_ROWS / 2.0f
    };
    self->super.frame.origin = origin;

    if (MELRectangleOriginIsTopLeftContainsPoint((MELRectangle) {
        .size = {
            .width = LCD_COLUMNS,
            .height = LCD_ROWS
        },
        .origin = MELPointZero
    }, origin)) {
        ShootingStyleShootFromSprite(&self->shootingStyle, &self->super, MEL_PI);
    }

    MELSpriteDraw(&self->super, sprite);
}
