//
//  satellite.c
//
//  Generated by Melia on 24/05/2023.
//

#include "satellite.h"

#include "aimedshootingstyle.h"
#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spritesatellite.h"
#include "../gen/spritebullet.h"

enum satellite_state {
    main,
    withdrawing,
};

struct satellite {
    MELSprite super;

    enum satellite_state state;
    uint8_t statePart;
    float ray;
    float strideDecimalFrom0;
    float strideDecimalTo0;
    ShootingStyle style;
    float time;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);
static void mainStatePart3(LCDSprite * _Nonnull sprite);
static void mainStatePart4(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct satellite * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass SatelliteClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

static const ShootingStyleDefinition kStyleDefinition = (ShootingStyleDefinition) {
    .bulletDefinition = &spriteBullet,
    .bulletAmount = 1,
    .bulletSpeed = 90,
    .shootInterval = 1.5f,
    .origin = ShotOriginFront,
    .damage = ENEMY_SATELLITE_BULLET_DAMAGE,
};

LCDSprite * _Nonnull SatelliteConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct satellite *self = playdate->system->realloc(NULL, sizeof(struct satellite));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &SatelliteClass;
    self->super.frame.origin.x = -48.0f;
    self->super.hitPoints = ENEMY_SATELLITE_HIT_POINTS;
    self->super.score = ENEMY_SATELLITE_SCORE;
    loadSpriteBulletPalette();
    AimedShootingStyleInit(&self->style, &kStyleDefinition);

    if (self->super.direction == MELDirectionUp) {
        self->super.frame.origin.y = 210.5f;
        self->ray = (self->super.frame.origin.y - self->super.instance->center.y) / 2.0f;
    } else {
        self->super.frame.origin.y = 29.5f;
        self->ray = (self->super.instance->center.y - self->super.frame.origin.y) / 2.0f;
    }
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct satellite *self = (struct satellite *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->ray);
    ShootingStyleSave(&self->style, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable SatelliteLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct satellite *self = playdate->system->realloc(NULL, sizeof(struct satellite));
    const enum satellite_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float ray = MELInputStreamReadFloat(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kStyleDefinition);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct satellite) {
        .super = {
            .class = &SatelliteClass
        },
        .state = state,
        .statePart = statePart,
        .ray = ray,
        .style = style,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &SatelliteClass) {
        playdate->system->error("Given sprite is not an instance of Satellite");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void goToCurrentState(struct satellite * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                case 3:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart3);
                    break;
                case 4:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart4);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = self->super.instance->center.x / 400.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // wait
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = (self->super.instance->center.x + 48.0f) / 150;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float x = MELFloatMin(newTime, duration) / duration;
        const float progress = 1 - cosf((x * 3.1415925f) / 2);
        self->time = newTime;

        self->super.frame.origin.x = -48.0f + (self->super.instance->center.x - -48.0f) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 3;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart3);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart3(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = (4.712389f * fabsf(self->ray)) / 150;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float x = MELFloatMin(newTime, duration) / duration;
        const float progress = sinf((x * 3.1415925f) / 2);
        self->time = newTime;

        self->super.frame.origin = (MELPoint) {
            .x = self->super.instance->center.x + cosf(progress * 3.1415925f - 3.1415925f / 2) * fabsf(self->ray),
            .y = self->super.instance->center.y - MELDirectionValues[self->super.direction] * self->ray + (sinf(progress * 3.1415925f - 3.1415925f / 2) * self->ray) * MELDirectionValues[self->super.direction]
        };
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // while
    self->statePart = 4;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart4);
    mainStatePart4(sprite);
}

static void mainStatePart4(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // while
    // shoot
    ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct satellite *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float x = MELFloatMin(newTime, duration) / duration;
        const float progress = x * x;
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + (480 - self->super.instance->center.x) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

