//
//  shark.c
//
//  Generated by Melia on 24/05/2023.
//

#include "shark.h"

#include "circularshootingstyle.h"
#include "../lib/subsprite.h"
#include "../gen/spritenames.h"
#include "../gen/spriteshark.h"
#include "../gen/spritebullet.h"

enum shark_state {
    main,
    withdrawing,
};

struct shark {
    MELSprite super;

    enum shark_state state;
    uint8_t statePart;
    float strideDecimalFrom0;
    ShootingStyle style;
    MELPoint target;
    float time;
    float wobble;
    float wobbleSpeed;
};

static const CircularShootingStyleDefinition kStyleDefinition = (CircularShootingStyleDefinition) {
    .super = {
        .origin = ShotOriginFront,
        .bulletDefinition = &spriteBullet,
        .bulletSpeed = 90.0f,
        .bulletAmount = 7,
        .damage = ENEMY_SHARK_BULLET_DAMAGE,
        .shootInterval = 0.5f,
    },
    .baseAngle = -MEL_PI_2,
    .angleIncrement = MEL_PI / 6.0f
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct shark * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass SharkClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

LCDSprite * _Nonnull SharkConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct shark *self = playdate->system->realloc(NULL, sizeof(struct shark));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &SharkClass;
    self->super.hitPoints = ENEMY_SHARK_HIT_POINTS;
    self->super.score = ENEMY_SHARK_SCORE;
    self->target = self->super.frame.origin;
    self->super.frame.origin.x = 460;
    self->wobble = 0;
    self->wobbleSpeed = MELRandomFloat(2.0f) - 1.0f;
    self->state = main;
    self->statePart = 0;
    loadSpriteBulletPalette();
    CircularShootingStyleInit(&self->style, &kStyleDefinition);
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct shark *self = (struct shark *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->strideDecimalFrom0);
    ShootingStyleSave(&self->style, outputStream);
    MELOutputStreamWritePoint(outputStream, self->target);
    MELOutputStreamWriteFloat(outputStream, self->time);
    MELOutputStreamWriteFloat(outputStream, self->wobble);
    MELOutputStreamWriteFloat(outputStream, self->wobbleSpeed);
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct shark *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &SharkClass) {
        playdate->system->error("Given sprite is not an instance of Shark");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

MELSprite * _Nullable SharkLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct shark *self = playdate->system->realloc(NULL, sizeof(struct shark));
    const enum shark_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float strideDecimalFrom0 = MELInputStreamReadFloat(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kStyleDefinition.super);
    const MELPoint target = MELInputStreamReadPoint(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);
    const float wobble = MELInputStreamReadFloat(inputStream);
    const float wobbleSpeed = MELInputStreamReadFloat(inputStream);

    *self = (struct shark) {
        .super = {
            .class = &SharkClass
        },
        .state = state,
        .statePart = statePart,
        .strideDecimalFrom0 = strideDecimalFrom0,
        .style = style,
        .target = target,
        .time = time,
        .wobble = wobble,
        .wobbleSpeed = wobbleSpeed,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct shark * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}


static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct shark *self = playdate->sprite->getUserdata(sprite);

    // during
    self->strideDecimalFrom0 = self->super.instance->center.y + 64.0f * self->wobbleSpeed;
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct shark *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float x = MELFloatMin(newTime, duration) / duration;
        const float progress = 1 + 2.70158f * (powf((x - 1), 3)) + 1.70158f * (powf((x - 1), 2));
        self->time = newTime;

        self->super.frame.origin.x = 460 + (self->super.instance->center.x - 460) * progress;
        self->super.frame.origin.y = self->strideDecimalFrom0 + (self->super.instance->center.y - self->strideDecimalFrom0) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // during
    self->time = 0;
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct shark *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 4.0f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        self->time = newTime;

        // shoot
        ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
        self->super.frame.origin = (MELPoint) {
            .x = self->super.frame.origin.x + DELTA * 5.0f,
            .y = self->super.instance->center.y + sinf(self->wobble) * 6.0f
        };
        self->wobble = self->wobble + DELTA * self->wobbleSpeed;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    self->state = withdrawing;
    self->statePart = 0;
    goToCurrentState(self, sprite);
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct shark *self = playdate->sprite->getUserdata(sprite);

    // during
    self->strideDecimalFrom0 = self->super.frame.origin.x;
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct shark *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 2.5f;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float x = MELFloatMin(newTime, duration) / duration;
        const float progress = ((2.70158f * x) * x) * x - (1.70158f * x) * x;
        self->time = newTime;

        self->super.frame.origin.x = self->strideDecimalFrom0 + (-60 - self->strideDecimalFrom0) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

