//
//  stationary.c
//
//  Generated by Melia on 24/05/2023.
//

#include "stationary.h"

#include "aimedshootingstyle.h"
#include "rocketshootingstyle.h"
#include "../gen/spritebullet.h"
#include "../gen/spriterocket.h"
#include "../gen/spriteturtleshell.h"

enum stationary_state {
    main,
    withdrawing,
};

struct stationary {
    MELSprite super;

    enum stationary_state state;
    uint8_t statePart;
    ShootingStyle style;
    float time;
};

static void mainStatePart0(LCDSprite * _Nonnull sprite);
static void mainStatePart1(LCDSprite * _Nonnull sprite);
static void mainStatePart2(LCDSprite * _Nonnull sprite);

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite);
static void withdrawingStatePart1(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct stationary * _Nonnull self, LCDSprite * _Nonnull sprite);
static void withdraw(LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass StationaryClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
    .withdraw = withdraw,
};

static const ShootingStyleDefinition kRocketDefinition = (ShootingStyleDefinition) {
    .origin = ShotOriginFront,
    .bulletDefinition = &spriteRocket,
    .bulletAmount = 1,
    .shootInterval = 5.0f,
    .translation = {
        .x = 10.0f,
        .y = 0.0f
    },
    .damage = BOSS_MID_ROCKET_DAMAGE,
};

LCDSprite * _Nonnull StationaryConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct stationary *self = playdate->system->realloc(NULL, sizeof(struct stationary));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &StationaryClass;
    self->super.hitPoints = ENEMY_STATIONARY_HIT_POINTS;
    self->super.score = ENEMY_STATIONARY_SCORE;
    self->super.frame.origin.x = 442.0f;
    loadSpriteRocketPalette();
    RocketShootingStyleInit(&self->style, &kRocketDefinition);
    self->state = main;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart0);
    playdate->sprite->setZIndex(sprite, ZINDEX_ENEMIES);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct stationary *self = (struct stationary *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    ShootingStyleSave(&self->style, outputStream);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable StationaryLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct stationary *self = playdate->system->realloc(NULL, sizeof(struct stationary));
    const enum stationary_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    loadSpriteBulletPalette();
    const ShootingStyle style = ShootingStyleLoad(inputStream, &kRocketDefinition);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct stationary) {
        .super = {
            .class = &StationaryClass
        },
        .state = state,
        .statePart = statePart,
        .style = style,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void withdraw(LCDSprite * _Nonnull sprite) {
    struct stationary *self = playdate->sprite->getUserdata(sprite);
#if CHECK_CLASS_CAST
    if (self->super.class != &StationaryClass) {
        playdate->system->error("Given sprite is not an instance of Stationary");
    }
#endif
    self->state = withdrawing;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
}

static void goToCurrentState(struct stationary * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case withdrawing:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart1);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, withdrawingStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, mainStatePart0);
                    break;
            }
            break;
    }
}

static void mainStatePart0(LCDSprite * _Nonnull sprite) {
    struct stationary *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void mainStatePart1(LCDSprite * _Nonnull sprite) {
    struct stationary *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = (400 - self->super.instance->center.x) / 100;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = 442.0f + (self->super.instance->center.x - 442.0f) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // while
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &mainStatePart2);
    mainStatePart2(sprite);
}

static void mainStatePart2(LCDSprite * _Nonnull sprite) {
    struct stationary *self = playdate->sprite->getUserdata(sprite);

    // while
    // shoot
    ShootingStyleShootFromSprite(&self->style, &self->super, MEL_PI);
    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart0(LCDSprite * _Nonnull sprite) {
    struct stationary *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &withdrawingStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void withdrawingStatePart1(LCDSprite * _Nonnull sprite) {
    struct stationary *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = (400 - self->super.instance->center.x) / 100;
    if (self->time < duration) {
        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        self->super.frame.origin.x = self->super.instance->center.x + (442.0f - self->super.instance->center.x) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    MELSpriteDealloc(sprite);
}

