//
//  win_lose_message.c
//
//  Generated by Melia on 13/01/2024.
//

#include "win_lose_message.h"

#include "cardsprite.h"

#include "../gen/spritenames.h"
#include "../gen/spritewinlosemessage.h"

enum win_lose_message_state {
    lose,
    win,
};

struct win_lose_message {
    MELSprite super;

    Board * _Nonnull board;
    enum win_lose_message_state state;
    uint8_t statePart;
    float time;
};

static void loseStatePart0(LCDSprite * _Nonnull sprite);
static void loseStatePart1(LCDSprite * _Nonnull sprite);
static void loseStatePart2(LCDSprite * _Nonnull sprite);

static void winStatePart0(LCDSprite * _Nonnull sprite);
static void winStatePart1(LCDSprite * _Nonnull sprite);
static void winStatePart2(LCDSprite * _Nonnull sprite);

static void goToCurrentState(struct win_lose_message * _Nonnull self, LCDSprite * _Nonnull sprite);
static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream);

static const MELSpriteClass WinLoseMessageClass = (MELSpriteClass) {
    .destroy = MELSpriteDealloc,
    .save = save,
};

LCDSprite * _Nonnull WinLoseMessageConstructor(MELSpriteDefinition * _Nonnull definition, MELSpriteInstance * _Nonnull instance) {
    struct win_lose_message *self = playdate->system->realloc(NULL, sizeof(struct win_lose_message));
    LCDSprite *sprite = MELSpriteInit(&self->super, definition, instance);
    self->super.class = &WinLoseMessageClass;
    self->super.frame.origin.y = -48.5f;
    self->state = lose;
    self->statePart = 0;
    playdate->sprite->setUpdateFunction(sprite, &loseStatePart0);
    return sprite;
}

LCDSprite * _Nonnull WinLoseMessageConstructorWithBoard(Board * _Nonnull board, MELBoolean hasWin) {
    struct win_lose_message *self = playdate->system->realloc(NULL, sizeof(struct win_lose_message));

    loadSpriteWinLoseMessagePalette();
    MELRectangle boardFrame = board->super.frame;
    LCDSprite *sprite = MELSpriteInitWithCenter(&self->super, &spriteWinLoseMessage, (MELPoint) {
        .x = boardFrame.origin.x + BOARD_WIDTH / 2,
        .y = -48.5f,
    });
    self->super.class = &WinLoseMessageClass;
    self->board = board;
    self->statePart = 0;
    self->state = hasWin ? win : lose;
    goToCurrentState(self, sprite);
    playdate->sprite->setZIndex(sprite, ZINDEX_WIN_LOSE);
    LCDSpriteRefListPush(&currentScene->sprites, sprite);
    return sprite;
}

static void save(MELSprite * _Nonnull sprite, MELOutputStream * _Nonnull outputStream) {
    struct win_lose_message *self = (struct win_lose_message *)sprite;
    MELOutputStreamWriteByte(outputStream, self->state);
    MELOutputStreamWriteByte(outputStream, self->statePart);
    MELOutputStreamWriteFloat(outputStream, self->time);
}

MELSprite * _Nullable WinLoseMessageLoader(MELSpriteDefinition * _Nonnull definition, LCDSprite * _Nonnull sprite, MELInputStream * _Nonnull inputStream) {
    struct win_lose_message *self = playdate->system->realloc(NULL, sizeof(struct win_lose_message));
    const enum win_lose_message_state state = MELInputStreamReadByte(inputStream);
    const uint8_t statePart = MELInputStreamReadByte(inputStream);
    const float time = MELInputStreamReadFloat(inputStream);

    *self = (struct win_lose_message) {
        .super = {
            .class = &WinLoseMessageClass
        },
        .state = state,
        .statePart = statePart,
        .time = time,
    };
    goToCurrentState(self, sprite);
    return &self->super;
}

static void goToCurrentState(struct win_lose_message * _Nonnull self, LCDSprite * _Nonnull sprite) {
    switch (self->state) {
        case win:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, winStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, winStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, winStatePart0);
                    break;
            }
            break;
        default:
            switch (self->statePart) {
                case 1:
                    playdate->sprite->setUpdateFunction(sprite, loseStatePart1);
                    break;
                case 2:
                    playdate->sprite->setUpdateFunction(sprite, loseStatePart2);
                    break;
                default:
                    playdate->sprite->setUpdateFunction(sprite, loseStatePart0);
                    break;
            }
            break;
    }
}

static void loseStatePart0(LCDSprite * _Nonnull sprite) {
    struct win_lose_message *self = playdate->sprite->getUserdata(sprite);

    MELSpriteSetAnimation(&self->super, AnimationNameWalk);
    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &loseStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void loseStatePart1(LCDSprite * _Nonnull sprite) {
    struct win_lose_message *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float oldProgress = MELEaseInOut(0, duration, self->time);
        const int oldRow = BOARD_ROWS * oldProgress;

        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseOutBounce(0, duration, newTime);
        const int row = BOARD_ROWS * MELEaseInOut(0, duration, newTime);
        self->time = newTime;

        if (row < BOARD_ROWS && (row == 0 || oldRow != row)) {
            BoardChangeCardsToChipAtRow(self->board, row);
        }

        const float targetY = TILE_SIZE + 48.5f;
        self->super.frame.origin.y = -48.5f + (targetY - -48.5f) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // while
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &loseStatePart2);
    loseStatePart2(sprite);
}

static void loseStatePart2(LCDSprite * _Nonnull sprite) {
    struct win_lose_message *self = playdate->sprite->getUserdata(sprite);

    // while
    // wait
    MELSpriteDraw(&self->super, sprite);
}

static void winStatePart0(LCDSprite * _Nonnull sprite) {
    struct win_lose_message *self = playdate->sprite->getUserdata(sprite);

    // during
    self->time = 0;
    self->statePart = 1;
    playdate->sprite->setUpdateFunction(sprite, &winStatePart1);

    MELSpriteDraw(&self->super, sprite);
}

static void winStatePart1(LCDSprite * _Nonnull sprite) {
    struct win_lose_message *self = playdate->sprite->getUserdata(sprite);

    // during
    const float duration = 1.0f;
    if (self->time < duration) {
        const float oldProgress = MELEaseInOut(0, duration, self->time);
        const int oldRow = BOARD_ROWS * oldProgress;

        const float newTime = MELFloatMin(self->time + DELTA, duration);
        const float progress = MELEaseInOut(0, duration, newTime);
        const int row = BOARD_ROWS * progress;
        self->time = newTime;

        if (row < BOARD_ROWS && (row == 0 || oldRow != row)) {
            BoardBounceCardsAtRow(self->board, row);
        }

        const float targetY = TILE_SIZE + 48.5f;
        self->super.frame.origin.y = -48.5f + (targetY - -48.5f) * progress;
        MELSpriteDraw(&self->super, sprite);
        return;
    }
    // while
    self->statePart = 2;
    playdate->sprite->setUpdateFunction(sprite, &winStatePart2);
    winStatePart2(sprite);
}

static void winStatePart2(LCDSprite * _Nonnull sprite) {
    struct win_lose_message *self = playdate->sprite->getUserdata(sprite);

    // while
    // wait
    MELSpriteDraw(&self->super, sprite);
}

